export const INDEX_TO_NAME = {
    0: "the fool",
    1: "the magician",
    2: "the high priestess",
    3: "the empress",
    4: "the emperor",
    5: "the hierophant",
    6: "the lovers",
    7: "the chariot",
    8: "strength",
    9: "the hermit",
    10: "wheel of fortune",
    11: "justice",
    12: "the hanged man",
    13: "death",
    14: "temperance",
    15: "the devil",
    16: "the tower",
    17: "the star",
    18: "the moon",
    19: "the sun",
    20: "judgement",
    21: "the world",
    22: "ace of wands",
    23: "two of wands",
    24: "three of wands",
    25: "four of wands",
    26: "five of wands",
    27: "six of wands",
    28: "seven of wands",
    29: "eight of wands",
    30: "nine of wands",
    31: "ten of wands",
    32: "page of wands",
    33: "knight of wands",
    34: "queen of wands",
    35: "king of wands",
    36: "ace of cups",
    37: "two of cups",
    38: "three of cups",
    39: "four of cups",
    40: "five of cups",
    41: "six of cups",
    42: "seven of cups",
    43: "eight of cups",
    44: "nine of cups",
    45: "ten of cups",
    46: "page of cups",
    47: "knight of cups",
    48: "queen of cups",
    49: "king of cups",
    50: "ace of swords",
    51: "two of swords",
    52: "three of swords",
    53: "four of swords",
    54: "five of swords",
    55: "six of swords",
    56: "seven of swords",
    57: "eight of swords",
    58: "nine of swords",
    59: "ten of swords",
    60: "page of swords",
    61: "knight of swords",
    62: "queen of swords",
    63: "king of swords",
    64: "ace of pentacles",
    65: "two of pentacles",
    66: "three of pentacles",
    67: "four of pentacles",
    68: "five of pentacles",
    69: "six of pentacles",
    70: "seven of pentacles",
    71: "eight of pentacles",
    72: "nine of pentacles",
    73: "ten of pentacles",
    74: "page of pentacles",
    75: "knight of pentacles",
    76: "queen of pentacles",
    77: "king of pentacles"
};
