export const hinduDeitiesDetail = {
    "Ganesha": {
        "name": "Ganesha",
        "coreIntentions": "success, wisdom, clear path, breakthrough, beginnings",
        "coreEssence": "Removes what blocks your path",
        "meaning": "This remover of obstacles dances at the threshold of every new beginning, embodying the divine paradox that wisdom often comes wrapped in unexpected forms. He represents the sacred gateway between intention and manifestation—teaching that obstacles are merely unopened doors waiting for the right key of understanding.",
        "number": 0,
        "title": "Lord of Sacred Beginnings",
        "coreMeaning": "New Beginnings — Obstacle Removal, Childlike Wisdom, and Trust in the Unknown",
        "keywords": [
            "beginning",
            "innocence",
            "spontaneity",
            "free spirit",
            "adventure",
            "journey",
            "leap of faith",
            "new start",
            "fresh",
            "naive",
            "optimistic",
            "carefree",
            "risk",
            "potential",
            "youth",
            "inexperience",
            "originality",
            "freedom",
            "wanderer",
            "trust",
            "courage",
            "unknown",
            "foolish",
            "playful",
            "curious",
            "openness",
            "wonder",
            "possibilities",
            "fearless",
            "childlike",
            "pure"
        ]
    },
    "Vishwakarma": {
        "name": "Vishwakarma",
        "coreIntentions": "skill, craftsmanship, creation, excellence, innovation",
        "coreEssence": "Builds your dreams into reality",
        "meaning": "This divine architect transforms thought into form through sacred craftsmanship, building bridges between imagination and reality. He represents the creative principle that shapes worlds—teaching that we are co-creators with the divine, manifesting through skillful action.",
        "number": 1,
        "title": "The Cosmic Craftsman",
        "coreMeaning": "Manifestation — Divine Tools, Skillful Creation, and Will Made Form",
        "keywords": [
            "manifestation",
            "power",
            "skill",
            "concentration",
            "action",
            "resourcefulness",
            "willpower",
            "creation",
            "ability",
            "talent",
            "transformation",
            "focus",
            "confidence",
            "mastery",
            "will",
            "divine tools",
            "magic",
            "alchemy",
            "intention",
            "conscious",
            "awareness",
            "control",
            "capability",
            "competence",
            "achievement",
            "realization",
            "potential",
            "initiative",
            "determination"
        ]
    },
    "Saraswati": {
        "name": "Saraswati",
        "coreIntentions": "knowledge, wisdom, eloquence, creativity, learning",
        "coreEssence": "Flows wisdom through creativity",
        "meaning": "This keeper of hidden knowledge flows between seen and unseen realms, her veena playing the frequencies only the soul can hear. She represents intuitive wisdom—teaching that the deepest truths bypass the mind to whisper directly to consciousness.",
        "number": 2,
        "title": "Guardian of Sacred Mysteries",
        "coreMeaning": "Intuition — Hidden Knowledge, Inner Wisdom, and Mystical Understanding",
        "keywords": [
            "intuition",
            "mystery",
            "subconscious",
            "higher power",
            "wisdom",
            "secrets",
            "inner voice",
            "unconscious",
            "divine feminine",
            "spirituality",
            "sacred knowledge",
            "psychic",
            "dreams",
            "hidden",
            "receptive",
            "passive",
            "stillness",
            "meditation",
            "lunar",
            "mystical",
            "esoteric",
            "veiled",
            "inner knowing",
            "patience",
            "silence",
            "duality",
            "guardian",
            "threshold"
        ]
    },
    "Lakshmi": {
        "name": "Lakshmi",
        "coreIntentions": "prosperity, abundance, wealth, fortune, generosity",
        "coreEssence": "Attracts abundance naturally",
        "meaning": "This golden mother nurtures all forms of abundance, from material wealth to spiritual richness, teaching that prosperity flows where gratitude dwells. She represents creative abundance—showing that we birth beauty into the world through appreciation of what already is.",
        "number": 3,
        "title": "Mother of Infinite Wealth",
        "coreMeaning": "Abundance — Material and Spiritual Prosperity, Fertility, and Creative Power",
        "keywords": [
            "fertility",
            "abundance",
            "motherhood",
            "nature",
            "nurturing",
            "creativity",
            "beauty",
            "femininity",
            "luxury",
            "sensuality",
            "harvest",
            "pregnancy",
            "material wealth",
            "comfort",
            "earthly pleasures",
            "growth",
            "nourishment",
            "maternal",
            "venus",
            "love",
            "harmony",
            "receptivity",
            "compassion",
            "unconditional love",
            "divine feminine",
            "creation",
            "birth",
            "prosperity"
        ]
    },
    "Indra": {
        "name": "Indra",
        "coreIntentions": "power, victory, protection, leadership, strength",
        "coreEssence": "Commands your inner storms",
        "meaning": "This king of heaven maintains cosmic order through righteous authority, his thunderbolt establishing divine law across all realms. He represents sacred leadership—teaching that true power protects the vulnerable and serves the greater harmony.",
        "number": 4,
        "title": "Emperor of Heaven's Order",
        "coreMeaning": "Authority — Divine Leadership, Protective Power, and Established Order",
        "keywords": [
            "authority",
            "structure",
            "control",
            "father figure",
            "leadership",
            "stability",
            "power",
            "protection",
            "discipline",
            "provider",
            "establishment",
            "logic",
            "foundation",
            "order",
            "masculine",
            "rules",
            "boundaries",
            "strategy",
            "ambition",
            "rational",
            "government",
            "law",
            "tradition",
            "security",
            "dominance",
            "achievement",
            "material success",
            "sovereignty"
        ]
    },
    "Brihaspati": {
        "name": "Brihaspati",
        "coreIntentions": "wisdom, guidance, teaching, clarity, understanding",
        "coreEssence": "Guides with wise counsel",
        "meaning": "This guru of the gods bridges celestial wisdom with earthly understanding, making the sacred accessible through teaching. He represents spiritual tradition—showing how ancient truths remain alive when transmitted through devoted hearts.",
        "number": 5,
        "title": "Guru of Immortal Wisdom",
        "coreMeaning": "Teaching — Spiritual Wisdom, Sacred Tradition, and Divine Guidance",
        "keywords": [
            "tradition",
            "conformity",
            "institution",
            "education",
            "belief system",
            "spiritual wisdom",
            "religious",
            "ceremony",
            "conventional",
            "mentor",
            "teaching",
            "orthodoxy",
            "marriage",
            "commitment",
            "society",
            "approval",
            "tradition",
            "moral",
            "ethics",
            "values",
            "doctrine",
            "dogma",
            "ritual",
            "sacred",
            "guidance",
            "counsel",
            "established order",
            "spiritual authority"
        ]
    },
    "Krishna Radha": {
        "name": "Krishna Radha",
        "coreIntentions": "devotion, love, playfulness, joy, union",
        "coreEssence": "Plays divine love's melody",
        "meaning": "This eternal romance demonstrates love as the highest spiritual path, where human emotion becomes a gateway to divine union. They represent sacred partnership—teaching that in true love, the boundaries between devotee and deity, lover and beloved, dissolve completely.",
        "number": 6,
        "title": "The Eternal Beloveds",
        "coreMeaning": "Sacred Union — Divine Love, Soul Partnership, and Conscious Choice",
        "keywords": [
            "love",
            "relationships",
            "choices",
            "alignment",
            "values",
            "partnership",
            "union",
            "attraction",
            "harmony",
            "soulmate",
            "romance",
            "sexuality",
            "passion",
            "desire",
            "commitment",
            "communication",
            "duality",
            "balance",
            "decisions",
            "crossroads",
            "temptation",
            "free will",
            "personal beliefs",
            "moral choices",
            "connection",
            "intimacy",
            "trust",
            "vulnerability"
        ]
    },
    "Durga": {
        "name": "Durga",
        "coreIntentions": "protection, strength, courage, victory, power",
        "coreEssence": "Conquers impossible battles",
        "meaning": "This unstoppable force rides into battle when dharma faces annihilation, wielding the combined powers of all gods. She represents righteous victory—teaching that when we fight for truth, the entire universe conspires to ensure our triumph.",
        "number": 7,
        "title": "The Invincible Protector",
        "coreMeaning": "Victory — Divine Intervention, Assured Success, and Dharmic Triumph",
        "keywords": [
            "control",
            "willpower",
            "determination",
            "success",
            "ambition",
            "focus",
            "victory",
            "assertion",
            "direction",
            "self-discipline",
            "confidence",
            "conquest",
            "overcoming",
            "hard work",
            "triumph",
            "journey",
            "progress",
            "warrior",
            "vehicle",
            "mastery",
            "drive",
            "momentum",
            "opposing forces",
            "balance",
            "swift action",
            "achievement",
            "perseverance",
            "courage"
        ]
    },
    "Hanuman": {
        "name": "Hanuman",
        "coreIntentions": "devotion, strength, service, courage, faith",
        "coreEssence": "Leaps over any obstacle",
        "meaning": "This embodiment of devotion discovers infinite strength through complete surrender, proving that love makes the impossible possible. He represents heart-centered power—teaching that true strength flows not from ego but from selfless service to the divine.",
        "number": 8,
        "title": "Champion of Boundless Devotion",
        "coreMeaning": "Strength — Devotional Power, Heart Courage, and Love's Might",
        "keywords": [
            "strength",
            "courage",
            "patience",
            "compassion",
            "control",
            "inner strength",
            "gentle power",
            "persuasion",
            "influence",
            "taming",
            "confidence",
            "self-control",
            "determination",
            "fortitude",
            "resilience",
            "endurance",
            "heart over mind",
            "soft control",
            "feminine power",
            "grace under pressure",
            "moral courage",
            "kindness",
            "understanding",
            "forgiveness",
            "healing",
            "integration",
            "beast taming",
            "raw power"
        ]
    },
    "Dakshinamurthy": {
        "name": "Dakshinamurthy",
        "coreIntentions": "wisdom, silence, understanding, knowledge, truth",
        "coreEssence": "Teaches through sacred silence",
        "meaning": "This silent teacher sits beneath the cosmic tree, transmitting wisdom through silence more profound than words. He represents inner illumination—showing that ultimate truth reveals itself in solitude to those who turn awareness inward.",
        "number": 9,
        "title": "The Wordless Teacher",
        "coreMeaning": "Inner Light — Silent Wisdom, Solitary Path, and Self-Realization",
        "keywords": [
            "solitude",
            "introspection",
            "guidance",
            "wisdom",
            "inner light",
            "soul searching",
            "meditation",
            "self-discovery",
            "contemplation",
            "isolation",
            "withdrawal",
            "prudence",
            "discretion",
            "seeking",
            "spiritual quest",
            "inner voice",
            "teacher",
            "mentor",
            "enlightenment",
            "truth seeking",
            "patience",
            "inner journey",
            "reflection",
            "philosophy",
            "maturity",
            "experience",
            "lantern",
            "illumination"
        ]
    },
    "Vishnu": {
        "name": "Vishnu",
        "coreIntentions": "preservation, protection, stability, order, peace",
        "coreEssence": "Preserves what truly matters",
        "meaning": "This cosmic maintainer dreams reality in endless cycles, each breath sustaining worlds, each avatar addressing the age's need. He represents divine rhythm—teaching that preservation requires constant adaptation and that stability comes through flowing with change.",
        "number": 10,
        "title": "Keeper of Cosmic Wheels",
        "coreMeaning": "Cycles — Divine Order, Karmic Wheels, and Eternal Return",
        "keywords": [
            "cycles",
            "change",
            "fate",
            "luck",
            "fortune",
            "karma",
            "turning point",
            "destiny",
            "opportunities",
            "life cycles",
            "ups and downs",
            "movement",
            "chance",
            "synchronicity",
            "pivotal moment",
            "evolution",
            "progress",
            "seasons",
            "time",
            "revolution",
            "unexpected",
            "gambling",
            "risk",
            "wheel turning",
            "cosmic forces",
            "divine timing",
            "breakthrough",
            "fortune's wheel"
        ]
    },
    "Dharmaraja": {
        "name": "Dharmaraja",
        "coreIntentions": "justice, truth, fairness, integrity, dharma",
        "coreEssence": "Upholds your inner law",
        "meaning": "This impartial judge weighs every action on the scales of cosmic law, ensuring perfect justice without vengeance. He represents karmic balance—teaching that the universe maintains harmony through consequences that educate rather than punish.",
        "number": 11,
        "title": "Guardian of Cosmic Justice",
        "coreMeaning": "Justice — Karmic Law, Divine Balance, and Truth's Triumph",
        "keywords": [
            "justice",
            "fairness",
            "truth",
            "law",
            "balance",
            "accountability",
            "karma",
            "cause and effect",
            "integrity",
            "honesty",
            "responsibility",
            "legal matters",
            "decision",
            "impartiality",
            "objectivity",
            "ethics",
            "consequences",
            "clarity",
            "court",
            "judgment",
            "equilibrium",
            "scales",
            "sword",
            "divine justice",
            "moral law",
            "righteousness",
            "adjustment",
            "correction"
        ]
    },
    "Bhagirath": {
        "name": "Bhagirath",
        "coreIntentions": "perseverance, dedication, breakthrough, patience, reward",
        "coreEssence": "Brings heaven to earth",
        "meaning": "This devoted prince performed thousand-year penance to bring Ganga to earth, showing how sacrifice serves collective salvation. He represents conscious surrender—teaching that some victories require us to pause our personal desires for universal benefit.",
        "number": 12,
        "title": "The Patient Penitent",
        "coreMeaning": "Sacrifice — Spiritual Suspension, Selfless Service, and New Perspective",
        "keywords": [
            "sacrifice",
            "suspension",
            "letting go",
            "surrender",
            "new perspective",
            "waiting",
            "patience",
            "martyrdom",
            "release",
            "reversal",
            "contemplation",
            "limbo",
            "transition",
            "paradox",
            "enlightenment",
            "different viewpoint",
            "pause",
            "spiritual growth",
            "wisdom",
            "trials",
            "selflessness",
            "metamorphosis",
            "breaking patterns",
            "seeing differently",
            "voluntary sacrifice",
            "divine perspective",
            "illumination",
            "rebirth pending"
        ]
    },
    "Kali": {
        "name": "Kali",
        "coreIntentions": "release, transformation, protection, fearlessness, power",
        "coreEssence": "Destroys to recreate",
        "meaning": "This dancer on time's edge destroys illusion with fierce compassion, her garland of skulls marking ego-deaths that birth truth. She represents total transformation—teaching that what terrifies the false self liberates the eternal soul.",
        "number": 13,
        "title": "Mother of Sacred Destruction",
        "coreMeaning": "Death/Rebirth — Ego Dissolution, Time's Power, and Liberation Through Loss",
        "keywords": [
            "transformation",
            "endings",
            "beginnings",
            "change",
            "transition",
            "release",
            "metamorphosis",
            "rebirth",
            "renewal",
            "regeneration",
            "cycles",
            "mortality",
            "letting go",
            "severance",
            "conclusion",
            "closure",
            "elimination",
            "inevitable change",
            "profound change",
            "phoenix",
            "resurrection",
            "clearing",
            "purging",
            "evolution",
            "revolution",
            "death and rebirth",
            "major transition",
            "transformation"
        ]
    },
    "Ardhanarishvara": {
        "name": "Ardhanarishvara",
        "coreIntentions": "balance, unity, wholeness, harmony, completion",
        "coreEssence": "Balances all opposites within",
        "meaning": "This perfect unity of Shiva-Shakti transcends duality in one form, masculine and feminine dancing as unified consciousness. Represents divine integration—teaching that wholeness emerges when we stop choosing sides and embrace all aspects within.",
        "number": 14,
        "title": "The Sacred Marriage",
        "coreMeaning": "Integration — Perfect Balance, Unity of Opposites, and Inner Alchemy",
        "keywords": [
            "balance",
            "moderation",
            "patience",
            "harmony",
            "alchemy",
            "healing",
            "integration",
            "middle path",
            "compromise",
            "peace",
            "tranquility",
            "adaptation",
            "coordination",
            "tempering",
            "blending",
            "synthesis",
            "equilibrium",
            "purpose",
            "meaning",
            "flow",
            "divine connection",
            "guardian angel",
            "higher learning",
            "philosophy",
            "fusion",
            "unification",
            "patience",
            "art"
        ]
    },
    "Mara": {
        "name": "Mara",
        "coreIntentions": "liberation, clarity, detachment, awareness, freedom",
        "coreEssence": "Shows where desire traps you",
        "meaning": "This lord of temptation reveals how desires forge our chains, yet also shows that recognizing bondage is freedom's first step. He represents the teaching shadow—showing that our demons are often our greatest teachers in disguise.",
        "number": 15,
        "title": "Master of Illusion's Web",
        "coreMeaning": "Bondage — Material Attachment, Desire's Chains, and Hidden Liberation",
        "keywords": [
            "bondage",
            "addiction",
            "sexuality",
            "materialism",
            "attachment",
            "restriction",
            "temptation",
            "shadow self",
            "obsession",
            "dependency",
            "illusion",
            "oppression",
            "powerlessness",
            "fear",
            "ignorance",
            "hopelessness",
            "violence",
            "chains",
            "vices",
            "excess",
            "enslavement",
            "lust",
            "earthly pleasure",
            "hedonism",
            "manipulation",
            "control",
            "darkness",
            "raw desire"
        ]
    },
    "Narasimha": {
        "name": "Narasimha",
        "coreIntentions": "protection, courage, intervention, justice, power",
        "coreEssence": "Protects with fierce compassion",
        "meaning": "This impossible avatar tears through reality's fabric when conventional forms cannot contain divine protection. He represents cosmic disruption—teaching that when evil seems invincible, divinity shatters all natural laws to restore dharma.",
        "number": 16,
        "title": "Destroyer of False Security",
        "coreMeaning": "Sudden Liberation — Divine Fury, Shattered Illusions, and Explosive Grace",
        "keywords": [
            "destruction",
            "upheaval",
            "chaos",
            "revelation",
            "awakening",
            "breakdown",
            "liberation",
            "sudden change",
            "crisis",
            "release",
            "downfall",
            "exposure",
            "disaster",
            "shock",
            "disruption",
            "lightning bolt",
            "ego death",
            "breakthrough",
            "truth revealed",
            "collapse",
            "foundation shaking",
            "catastrophe",
            "enlightenment",
            "divine intervention",
            "rebuilding",
            "clearing",
            "purification",
            "forced change"
        ]
    },
    "Tara": {
        "name": "Tara",
        "coreIntentions": "compassion, liberation, protection, healing, aid",
        "coreEssence": "Guides through life's ocean",
        "meaning": "This mother of compassion guides souls across samsara's ocean, her thousand arms ensuring none are left behind. She represents hope embodied—teaching that divine grace responds to sincere calls, taking whatever form her children need.",
        "number": 17,
        "title": "Star of Infinite Compassion",
        "coreMeaning": "Hope — Universal Compassion, Divine Grace, and Healing Light",
        "keywords": [
            "hope",
            "inspiration",
            "serenity",
            "healing",
            "renewal",
            "spirituality",
            "faith",
            "purpose",
            "guidance",
            "peace",
            "tranquility",
            "wishes",
            "optimism",
            "insight",
            "astronomy",
            "future",
            "calm",
            "free flowing",
            "blessings",
            "generosity",
            "water bearer",
            "aquarius",
            "wishes granted",
            "divine love",
            "protection",
            "good fortune",
            "spiritual guidance",
            "bright future"
        ]
    },
    "Soma": {
        "name": "Soma",
        "coreIntentions": "healing, peace, rejuvenation, longevity, calm",
        "coreEssence": "Heals through gentle coolness",
        "meaning": "This lunar deity of divine nectar rules the mysterious realm where intoxication becomes illumination. He represents the mystical path—teaching that consciousness has many states, and confusion often precedes the deepest clarity.",
        "number": 18,
        "title": "Lord of Sacred Intoxication",
        "coreMeaning": "Illusion — Mystical States, Hidden Truths, and Divine Madness",
        "keywords": [
            "illusion",
            "intuition",
            "dreams",
            "subconscious",
            "fear",
            "anxiety",
            "deception",
            "confusion",
            "imagination",
            "mystery",
            "unconscious",
            "secrets",
            "shadow work",
            "psychic",
            "lunar cycles",
            "feminine",
            "emotions",
            "night",
            "hidden enemies",
            "insecurity",
            "dark night of soul",
            "uncertainty",
            "fluctuation",
            "reflection",
            "projection",
            "instinct",
            "madness",
            "howling"
        ]
    },
    "Surya": {
        "name": "Surya",
        "coreIntentions": "vitality, health, clarity, power, radiance",
        "coreEssence": "Illuminates your true path",
        "meaning": "This source of all light rides across heaven in a chariot of dawn, dissolving darkness with the mere fact of his presence. He represents pure consciousness—teaching that enlightenment isn't achieved but revealed when clouds of ignorance part.",
        "number": 19,
        "title": "The Eternal Illuminator",
        "coreMeaning": "Enlightenment — Pure Consciousness, Joy, and Self-Realization",
        "keywords": [
            "joy",
            "success",
            "vitality",
            "enlightenment",
            "warmth",
            "happiness",
            "positivity",
            "celebration",
            "achievement",
            "radiance",
            "energy",
            "life",
            "consciousness",
            "clarity",
            "confidence",
            "optimism",
            "enthusiasm",
            "childlike wonder",
            "playfulness",
            "growth",
            "abundance",
            "truth",
            "glory",
            "triumph",
            "illumination",
            "good fortune",
            "contentment",
            "brilliance"
        ]
    },
    "Chitragupta": {
        "name": "Chitragupta",
        "coreIntentions": "accountability, clearing, truth, justice, balance",
        "coreEssence": "Records your soul's journey",
        "meaning": "This divine accountant reads from the book where every soul's story is written, calling each to remember their true purpose. He represents spiritual awakening—teaching that judgment day is simply the moment we fully see ourselves.",
        "number": 20,
        "title": "Keeper of Soul Records",
        "coreMeaning": "Awakening — Life Review, Soul Calling, and Karmic Reckoning",
        "keywords": [
            "judgment",
            "rebirth",
            "redemption",
            "awakening",
            "renewal",
            "reckoning",
            "absolution",
            "resurrection",
            "calling",
            "purpose",
            "forgiveness",
            "release",
            "transformation",
            "evaluation",
            "assessment",
            "decision",
            "karma",
            "inner calling",
            "revelation",
            "acceptance",
            "atonement",
            "final judgment",
            "trumpet call",
            "arising",
            "liberation",
            "cosmic consciousness",
            "divine calling",
            "fresh start"
        ]
    },
    "Nataraja": {
        "name": "Nataraja",
        "coreIntentions": "rhythm, transformation, dance, flow, liberation",
        "coreEssence": "Dances through destruction and creation",
        "meaning": "This cosmic dancer performs the eternal rhythm where end and beginning are one movement, creation and destruction mere steps in an infinite dance. He represents mastery of cycles—teaching that completion is transformation, and every ending births new worlds.",
        "number": 21,
        "title": "Lord of the Eternal Dance",
        "coreMeaning": "Completion — Cosmic Mastery, Full Circle, and New Spiral Beginning",
        "keywords": [
            "completion",
            "accomplishment",
            "fulfillment",
            "wholeness",
            "achievement",
            "integration",
            "travel",
            "unity",
            "closure",
            "success",
            "realization",
            "enlightenment",
            "cosmic consciousness",
            "celebration",
            "synthesis",
            "graduation",
            "triumph",
            "perfection",
            "harmony",
            "world travel",
            "global awareness",
            "full circle",
            "totality",
            "cosmic dance",
            "mastery",
            "attainment",
            "universe",
            "infinite possibility"
        ]
    }
}