// Complete Keywords for all Tarot cards (English)
// Key = card number in the 78-card deck (0-77)
// This file contains keywords for all Major Arcana (0-21) and significant Minor Arcana cards

export const tarotKeywords = {
    // MAJOR ARCANA (0-21)
    0: [ // The Fool
        "beginning",
        "innocence",
        "spontaneity",
        "free spirit",
        "adventure",
        "journey",
        "leap of faith",
        "new start",
        "fresh",
        "naive",
        "optimistic",
        "carefree",
        "risk",
        "potential",
        "youth",
        "inexperience",
        "originality",
        "freedom",
        "wanderer",
        "trust",
        "courage",
        "unknown",
        "foolish",
        "playful",
        "curious",
        "openness",
        "wonder",
        "possibilities",
        "fearless",
        "childlike",
        "pure"
    ],

    1: [ // The Magician
        "manifestation",
        "power",
        "skill",
        "concentration",
        "action",
        "resourcefulness",
        "willpower",
        "creation",
        "ability",
        "talent",
        "transformation",
        "focus",
        "confidence",
        "mastery",
        "will",
        "divine tools",
        "magic",
        "alchemy",
        "intention",
        "conscious",
        "awareness",
        "control",
        "capability",
        "competence",
        "achievement",
        "realization",
        "potential",
        "initiative",
        "determination"
    ],

    2: [ // The High Priestess
        "intuition",
        "mystery",
        "subconscious",
        "higher power",
        "wisdom",
        "secrets",
        "inner voice",
        "unconscious",
        "divine feminine",
        "spirituality",
        "sacred knowledge",
        "psychic",
        "dreams",
        "hidden",
        "receptive",
        "passive",
        "stillness",
        "meditation",
        "lunar",
        "mystical",
        "esoteric",
        "veiled",
        "inner knowing",
        "patience",
        "silence",
        "duality",
        "guardian",
        "threshold"
    ],

    3: [ // The Empress
        "fertility",
        "abundance",
        "motherhood",
        "nature",
        "nurturing",
        "creativity",
        "beauty",
        "femininity",
        "luxury",
        "sensuality",
        "harvest",
        "pregnancy",
        "material wealth",
        "comfort",
        "earthly pleasures",
        "growth",
        "nourishment",
        "maternal",
        "venus",
        "love",
        "harmony",
        "receptivity",
        "compassion",
        "unconditional love",
        "divine feminine",
        "creation",
        "birth",
        "prosperity"
    ],

    4: [ // The Emperor
        "authority",
        "structure",
        "control",
        "father figure",
        "leadership",
        "stability",
        "power",
        "protection",
        "discipline",
        "provider",
        "establishment",
        "logic",
        "foundation",
        "order",
        "masculine",
        "rules",
        "boundaries",
        "strategy",
        "ambition",
        "rational",
        "government",
        "law",
        "tradition",
        "security",
        "dominance",
        "achievement",
        "material success",
        "sovereignty"
    ],

    5: [ // The Hierophant
        "tradition",
        "conformity",
        "institution",
        "education",
        "belief system",
        "spiritual wisdom",
        "religious",
        "ceremony",
        "conventional",
        "mentor",
        "teaching",
        "orthodoxy",
        "marriage",
        "commitment",
        "society",
        "approval",
        "tradition",
        "moral",
        "ethics",
        "values",
        "doctrine",
        "dogma",
        "ritual",
        "sacred",
        "guidance",
        "counsel",
        "established order",
        "spiritual authority"
    ],

    6: [ // The Lovers
        "love",
        "relationships",
        "choices",
        "alignment",
        "values",
        "partnership",
        "union",
        "attraction",
        "harmony",
        "soulmate",
        "romance",
        "sexuality",
        "passion",
        "desire",
        "commitment",
        "communication",
        "duality",
        "balance",
        "decisions",
        "crossroads",
        "temptation",
        "free will",
        "personal beliefs",
        "moral choices",
        "connection",
        "intimacy",
        "trust",
        "vulnerability"
    ],

    7: [ // The Chariot
        "control",
        "willpower",
        "determination",
        "success",
        "ambition",
        "focus",
        "victory",
        "assertion",
        "direction",
        "self-discipline",
        "confidence",
        "conquest",
        "overcoming",
        "hard work",
        "triumph",
        "journey",
        "progress",
        "warrior",
        "vehicle",
        "mastery",
        "drive",
        "momentum",
        "opposing forces",
        "balance",
        "swift action",
        "achievement",
        "perseverance",
        "courage"
    ],

    8: [ // Strength
        "strength",
        "courage",
        "patience",
        "compassion",
        "control",
        "inner strength",
        "gentle power",
        "persuasion",
        "influence",
        "taming",
        "confidence",
        "self-control",
        "determination",
        "fortitude",
        "resilience",
        "endurance",
        "heart over mind",
        "soft control",
        "feminine power",
        "grace under pressure",
        "moral courage",
        "kindness",
        "understanding",
        "forgiveness",
        "healing",
        "integration",
        "beast taming",
        "raw power"
    ],

    9: [ // The Hermit
        "solitude",
        "introspection",
        "guidance",
        "wisdom",
        "inner light",
        "soul searching",
        "meditation",
        "self-discovery",
        "contemplation",
        "isolation",
        "withdrawal",
        "prudence",
        "discretion",
        "seeking",
        "spiritual quest",
        "inner voice",
        "teacher",
        "mentor",
        "enlightenment",
        "truth seeking",
        "patience",
        "inner journey",
        "reflection",
        "philosophy",
        "maturity",
        "experience",
        "lantern",
        "illumination"
    ],

    10: [ // Wheel of Fortune
        "cycles",
        "change",
        "fate",
        "luck",
        "fortune",
        "karma",
        "turning point",
        "destiny",
        "opportunities",
        "life cycles",
        "ups and downs",
        "movement",
        "chance",
        "synchronicity",
        "pivotal moment",
        "evolution",
        "progress",
        "seasons",
        "time",
        "revolution",
        "unexpected",
        "gambling",
        "risk",
        "wheel turning",
        "cosmic forces",
        "divine timing",
        "breakthrough",
        "fortune's wheel"
    ],

    11: [ // Justice
        "justice",
        "fairness",
        "truth",
        "law",
        "balance",
        "accountability",
        "karma",
        "cause and effect",
        "integrity",
        "honesty",
        "responsibility",
        "legal matters",
        "decision",
        "impartiality",
        "objectivity",
        "ethics",
        "consequences",
        "clarity",
        "court",
        "judgment",
        "equilibrium",
        "scales",
        "sword",
        "divine justice",
        "moral law",
        "righteousness",
        "adjustment",
        "correction"
    ],

    12: [ // The Hanged Man
        "sacrifice",
        "suspension",
        "letting go",
        "surrender",
        "new perspective",
        "waiting",
        "patience",
        "martyrdom",
        "release",
        "reversal",
        "contemplation",
        "limbo",
        "transition",
        "paradox",
        "enlightenment",
        "different viewpoint",
        "pause",
        "spiritual growth",
        "wisdom",
        "trials",
        "selflessness",
        "metamorphosis",
        "breaking patterns",
        "seeing differently",
        "voluntary sacrifice",
        "divine perspective",
        "illumination",
        "rebirth pending"
    ],

    13: [ // Death
        "transformation",
        "endings",
        "beginnings",
        "change",
        "transition",
        "release",
        "metamorphosis",
        "rebirth",
        "renewal",
        "regeneration",
        "cycles",
        "mortality",
        "letting go",
        "severance",
        "conclusion",
        "closure",
        "elimination",
        "inevitable change",
        "profound change",
        "phoenix",
        "resurrection",
        "clearing",
        "purging",
        "evolution",
        "revolution",
        "death and rebirth",
        "major transition",
        "transformation"
    ],

    14: [ // Temperance
        "balance",
        "moderation",
        "patience",
        "harmony",
        "alchemy",
        "healing",
        "integration",
        "middle path",
        "compromise",
        "peace",
        "tranquility",
        "adaptation",
        "coordination",
        "tempering",
        "blending",
        "synthesis",
        "equilibrium",
        "purpose",
        "meaning",
        "flow",
        "divine connection",
        "guardian angel",
        "higher learning",
        "philosophy",
        "fusion",
        "unification",
        "patience",
        "art"
    ],

    15: [ // The Devil
        "bondage",
        "addiction",
        "sexuality",
        "materialism",
        "attachment",
        "restriction",
        "temptation",
        "shadow self",
        "obsession",
        "dependency",
        "illusion",
        "oppression",
        "powerlessness",
        "fear",
        "ignorance",
        "hopelessness",
        "violence",
        "chains",
        "vices",
        "excess",
        "enslavement",
        "lust",
        "earthly pleasure",
        "hedonism",
        "manipulation",
        "control",
        "darkness",
        "raw desire"
    ],

    16: [ // The Tower
        "destruction",
        "upheaval",
        "chaos",
        "revelation",
        "awakening",
        "breakdown",
        "liberation",
        "sudden change",
        "crisis",
        "release",
        "downfall",
        "exposure",
        "disaster",
        "shock",
        "disruption",
        "lightning bolt",
        "ego death",
        "breakthrough",
        "truth revealed",
        "collapse",
        "foundation shaking",
        "catastrophe",
        "enlightenment",
        "divine intervention",
        "rebuilding",
        "clearing",
        "purification",
        "forced change"
    ],

    17: [ // The Star
        "hope",
        "inspiration",
        "serenity",
        "healing",
        "renewal",
        "spirituality",
        "faith",
        "purpose",
        "guidance",
        "peace",
        "tranquility",
        "wishes",
        "optimism",
        "insight",
        "astronomy",
        "future",
        "calm",
        "free flowing",
        "blessings",
        "generosity",
        "water bearer",
        "aquarius",
        "wishes granted",
        "divine love",
        "protection",
        "good fortune",
        "spiritual guidance",
        "bright future"
    ],

    18: [ // The Moon
        "illusion",
        "intuition",
        "dreams",
        "subconscious",
        "fear",
        "anxiety",
        "deception",
        "confusion",
        "imagination",
        "mystery",
        "unconscious",
        "secrets",
        "shadow work",
        "psychic",
        "lunar cycles",
        "feminine",
        "emotions",
        "night",
        "hidden enemies",
        "insecurity",
        "dark night of soul",
        "uncertainty",
        "fluctuation",
        "reflection",
        "projection",
        "instinct",
        "madness",
        "howling"
    ],

    19: [ // The Sun
        "joy",
        "success",
        "vitality",
        "enlightenment",
        "warmth",
        "happiness",
        "positivity",
        "celebration",
        "achievement",
        "radiance",
        "energy",
        "life",
        "consciousness",
        "clarity",
        "confidence",
        "optimism",
        "enthusiasm",
        "childlike wonder",
        "playfulness",
        "growth",
        "abundance",
        "truth",
        "glory",
        "triumph",
        "illumination",
        "good fortune",
        "contentment",
        "brilliance"
    ],

    20: [ // Judgement
        "judgment",
        "rebirth",
        "redemption",
        "awakening",
        "renewal",
        "reckoning",
        "absolution",
        "resurrection",
        "calling",
        "purpose",
        "forgiveness",
        "release",
        "transformation",
        "evaluation",
        "assessment",
        "decision",
        "karma",
        "inner calling",
        "revelation",
        "acceptance",
        "atonement",
        "final judgment",
        "trumpet call",
        "arising",
        "liberation",
        "cosmic consciousness",
        "divine calling",
        "fresh start"
    ],

    21: [ // The World
        "completion",
        "accomplishment",
        "fulfillment",
        "wholeness",
        "achievement",
        "integration",
        "travel",
        "unity",
        "closure",
        "success",
        "realization",
        "enlightenment",
        "cosmic consciousness",
        "celebration",
        "synthesis",
        "graduation",
        "triumph",
        "perfection",
        "harmony",
        "world travel",
        "global awareness",
        "full circle",
        "totality",
        "cosmic dance",
        "mastery",
        "attainment",
        "universe",
        "infinite possibility"
    ],

    // MINOR ARCANA - SIGNIFICANT CARDS

    // ACES - Pure elemental energy and new beginnings
    22: [ // Ace of Wands
        "inspiration",
        "new beginning",
        "creative spark",
        "potential",
        "passion",
        "enthusiasm",
        "initiative",
        "breakthrough",
        "opportunity",
        "courage",
        "growth",
        "birth",
        "innovation",
        "vitality",
        "fire energy",
        "divine spark",
        "motivation",
        "ambition",
        "raw power",
        "spontaneity",
        "spiritual gift",
        "awakening",
        "enterprise",
        "adventure"
    ],

    36: [ // Ace of Cups
        "new love",
        "emotional beginning",
        "intuition",
        "spiritual awakening",
        "creativity",
        "compassion",
        "emotional release",
        "joy",
        "inner peace",
        "fertility",
        "new relationship",
        "forgiveness",
        "divine love",
        "emotional renewal",
        "happiness",
        "fulfillment",
        "abundance",
        "healing",
        "receptivity",
        "grace",
        "blessing",
        "emotional gift",
        "psychic opening",
        "heart opening"
    ],

    50: [ // Ace of Swords
        "mental clarity",
        "breakthrough",
        "new idea",
        "truth",
        "justice",
        "mental force",
        "clear thinking",
        "communication",
        "new perspective",
        "realization",
        "power",
        "victory",
        "sharp mind",
        "decision",
        "cutting through",
        "insight",
        "intellect",
        "focus",
        "determination",
        "logic",
        "analysis",
        "revelation",
        "mental gift",
        "discernment"
    ],

    64: [ // Ace of Pentacles
        "new opportunity",
        "manifestation",
        "prosperity",
        "new job",
        "material gain",
        "abundance",
        "security",
        "potential wealth",
        "grounding",
        "new venture",
        "investment",
        "practical beginning",
        "tangible results",
        "material gift",
        "foundation",
        "health",
        "trust",
        "resources",
        "stability",
        "physical gift",
        "earthly blessing",
        "seed",
        "golden opportunity",
        "success"
    ],

    // COURT CARDS - PAGES (Messengers and Students)
    32: [ // Page of Wands
        "messenger",
        "enthusiasm",
        "exploration",
        "discovery",
        "free spirit",
        "adventure",
        "courage",
        "excitement",
        "new ideas",
        "creative spark",
        "inspiration",
        "good news",
        "passionate",
        "eager",
        "playful",
        "spontaneous",
        "optimistic",
        "fearless",
        "student of fire",
        "youthful energy",
        "fresh start",
        "creative message",
        "potential",
        "impulsive"
    ],

    46: [ // Page of Cups
        "emotional message",
        "intuition",
        "creativity",
        "sensitivity",
        "dreamer",
        "romantic",
        "gentle",
        "artistic",
        "psychic ability",
        "emotional beginning",
        "inner child",
        "imagination",
        "idealistic",
        "tender",
        "innocent",
        "loving message",
        "surprise",
        "synchronicity",
        "student of water",
        "emotional learning",
        "sweet",
        "vulnerable",
        "receptive",
        "poetic"
    ],

    60: [ // Page of Swords
        "vigilant",
        "curious",
        "mental energy",
        "new ideas",
        "communication",
        "truth seeker",
        "alert",
        "observant",
        "intellectual",
        "news",
        "gossip",
        "spy",
        "investigative",
        "questioning",
        "analytical",
        "student of air",
        "mental agility",
        "sharp wit",
        "defensive",
        "cautious",
        "messenger of truth",
        "youthful intellect",
        "restless mind",
        "inquisitive"
    ],

    74: [ // Page of Pentacles
        "student",
        "ambition",
        "new skill",
        "practical",
        "diligent",
        "studious",
        "apprentice",
        "manifestation",
        "planning",
        "opportunity",
        "loyal",
        "patient",
        "methodical",
        "grounded",
        "reliable",
        "student of earth",
        "material message",
        "scholarship",
        "dedication",
        "focus",
        "practical news",
        "beginner",
        "steady progress",
        "tangible goals"
    ],

    // COURT CARDS - KNIGHTS (Action and Quest)
    33: [ // Knight of Wands
        "adventure",
        "impulsive",
        "passionate",
        "energetic",
        "hot-tempered",
        "charming",
        "rebellious",
        "fearless",
        "confident",
        "daring",
        "action",
        "journey",
        "haste",
        "warrior of fire",
        "courageous",
        "risk-taker",
        "charismatic",
        "bold",
        "restless",
        "competitive",
        "traveler",
        "spontaneous action",
        "quest for passion",
        "fiery pursuit"
    ],

    47: [ // Knight of Cups
        "romantic",
        "charming",
        "imaginative",
        "sensitive",
        "artistic",
        "dreamer",
        "idealistic",
        "emotional quest",
        "knight in shining armor",
        "proposal",
        "invitation",
        "following heart",
        "creative",
        "intuitive",
        "graceful",
        "diplomatic",
        "seductive",
        "warrior of water",
        "emotional offer",
        "chivalrous",
        "poetic soul",
        "quest for love",
        "emotional pursuit",
        "visionary"
    ],

    61: [ // Knight of Swords
        "ambitious",
        "action-oriented",
        "driven",
        "fast-thinking",
        "assertive",
        "direct",
        "impatient",
        "intellectual",
        "courageous",
        "warrior of air",
        "swift action",
        "determined",
        "aggressive",
        "rushing forward",
        "single-minded",
        "authoritative",
        "mental force",
        "champion of truth",
        "quick decision",
        "charging ahead",
        "quest for truth",
        "mental pursuit",
        "brave",
        "fierce"
    ],

    75: [ // Knight of Pentacles
        "methodical",
        "reliable",
        "patient",
        "conservative",
        "dedicated",
        "persistent",
        "responsible",
        "hardworking",
        "practical",
        "routine",
        "steady progress",
        "warrior of earth",
        "dutiful",
        "thorough",
        "cautious",
        "trustworthy",
        "determined",
        "slow and steady",
        "enduring",
        "materialistic",
        "quest for stability",
        "physical pursuit",
        "unwavering",
        "disciplined"
    ],

    // COURT CARDS - QUEENS (Mastery through Intuition)
    34: [ // Queen of Wands
        "confident",
        "independent",
        "charismatic",
        "bold",
        "creative",
        "passionate",
        "warm",
        "vibrant",
        "courageous",
        "determined",
        "outgoing",
        "magnetic",
        "queen of fire",
        "optimistic",
        "friendly",
        "energetic",
        "inspiring",
        "generous",
        "wholehearted",
        "vivacious",
        "self-assured",
        "fertility",
        "leadership",
        "radiant"
    ],

    48: [ // Queen of Cups
        "compassionate",
        "intuitive",
        "nurturing",
        "emotional",
        "empathic",
        "psychic",
        "caring",
        "supportive",
        "healing",
        "queen of water",
        "sensitive",
        "loving",
        "creative",
        "dreamy",
        "romantic",
        "maternal",
        "spiritual",
        "receptive",
        "emotional intelligence",
        "wise woman",
        "heart-centered",
        "devoted",
        "gentle strength",
        "deep feeling"
    ],

    62: [ // Queen of Swords
        "perceptive",
        "independent",
        "clear boundaries",
        "direct communication",
        "intelligent",
        "unbiased",
        "truthful",
        "experienced",
        "queen of air",
        "sharp wit",
        "discerning",
        "objective",
        "sophisticated",
        "professional",
        "honest",
        "principled",
        "organized",
        "logical",
        "fair-minded",
        "mature wisdom",
        "mental clarity",
        "constructive criticism",
        "strategic",
        "dignified"
    ],

    76: [ // Queen of Pentacles
        "nurturing",
        "practical",
        "providing",
        "motherly",
        "down-to-earth",
        "resourceful",
        "queen of earth",
        "generous",
        "reliable",
        "warm-hearted",
        "sensible",
        "luxurious",
        "homely",
        "abundant",
        "security-focused",
        "business-minded",
        "fertile",
        "welcoming",
        "material comfort",
        "financial security",
        "nature-loving",
        "grounded wisdom",
        "prosperity",
        "supportive"
    ],

    // COURT CARDS - KINGS (Mastery through Control)
    35: [ // King of Wands
        "natural leader",
        "visionary",
        "entrepreneur",
        "charismatic",
        "bold",
        "inspiring",
        "confident",
        "king of fire",
        "generous",
        "motivating",
        "influential",
        "commanding",
        "optimistic",
        "adventurous",
        "passionate leader",
        "courageous",
        "pioneering",
        "ambitious",
        "creative vision",
        "masterful",
        "noble",
        "expansive",
        "authoritative",
        "protective"
    ],

    49: [ // King of Cups
        "emotional balance",
        "compassionate",
        "diplomatic",
        "calm",
        "caring",
        "tolerant",
        "king of water",
        "wise counselor",
        "emotionally stable",
        "generous",
        "reliable",
        "devoted",
        "family-oriented",
        "understanding",
        "artistic mastery",
        "emotional control",
        "mature emotions",
        "patient",
        "advisor",
        "spiritual wisdom",
        "healing presence",
        "benevolent",
        "supportive leader",
        "intuitive wisdom"
    ],

    63: [ // King of Swords
        "intellectual power",
        "authority",
        "truth",
        "justice",
        "analytical",
        "king of air",
        "ethical",
        "moral authority",
        "clear thinking",
        "rational",
        "assertive",
        "professional",
        "strategic",
        "impartial",
        "stern",
        "commanding",
        "mental discipline",
        "wise judgment",
        "law and order",
        "structured thinking",
        "expert",
        "decisive leader",
        "intellectual mastery",
        "fair"
    ],

    77: [ // King of Pentacles
        "wealth",
        "business success",
        "leadership",
        "security",
        "discipline",
        "abundance",
        "king of earth",
        "reliable",
        "generous provider",
        "practical wisdom",
        "enterprising",
        "steady",
        "masterful",
        "materialistic",
        "protective",
        "conservative",
        "established",
        "financial security",
        "empire builder",
        "patient investor",
        "grounded authority",
        "prosperous",
        "accomplished",
        "stable leadership"
    ],

    // SIGNIFICANT NUMBERED CARDS
    37: [ // Two of Cups
        "partnership",
        "union",
        "love",
        "attraction",
        "connection",
        "relationships",
        "harmony",
        "balance",
        "mutual respect",
        "soulmate",
        "romance",
        "friendship",
        "equality",
        "proposal",
        "engagement",
        "truce",
        "cooperation",
        "healing",
        "reconciliation",
        "chemistry",
        "mutual attraction",
        "unified",
        "bond",
        "sacred union"
    ],

    45: [ // Ten of Cups
        "happiness",
        "fulfillment",
        "emotional contentment",
        "family harmony",
        "divine love",
        "blissful relationships",
        "peace",
        "emotional abundance",
        "happy family",
        "rainbow",
        "wishes fulfilled",
        "joyful",
        "domestic bliss",
        "true happiness",
        "loving community",
        "emotional security",
        "happily ever after",
        "alignment",
        "gratitude",
        "celebration",
        "wholeness",
        "completion",
        "emotional success",
        "joy"
    ],

    52: [ // Three of Swords
        "heartbreak",
        "sorrow",
        "grief",
        "loss",
        "betrayal",
        "painful truth",
        "separation",
        "sadness",
        "tears",
        "loneliness",
        "depression",
        "emotional pain",
        "trauma",
        "hurt",
        "rejection",
        "suffering",
        "emotional release",
        "healing crisis",
        "harsh words",
        "conflict",
        "disappointment",
        "painful realization",
        "emotional wound",
        "heartache"
    ],

    56: [ // Seven of Swords
        "deception",
        "strategy",
        "sneakiness",
        "betrayal",
        "trickery",
        "lies",
        "manipulation",
        "cunning",
        "scheming",
        "dishonesty",
        "theft",
        "stealth",
        "acting alone",
        "hidden agenda",
        "escape",
        "avoidance",
        "getting away with something",
        "secret plan",
        "mental challenge",
        "outsmarting",
        "tactical",
        "evasion",
        "lone wolf",
        "diplomacy"
    ],

    59: [ // Ten of Swords
        "painful ending",
        "betrayal",
        "backstabbing",
        "defeat",
        "crisis",
        "bottoming out",
        "exhaustion",
        "dead end",
        "victim mentality",
        "rock bottom",
        "martyrdom",
        "dramatic ending",
        "overkill",
        "ruin",
        "failure",
        "collapse",
        "finality",
        "inevitable end",
        "hitting bottom",
        "nowhere to go but up",
        "darkest before dawn",
        "complete defeat",
        "transformation point",
        "rebirth pending"
    ],

    73: [ // Ten of Pentacles
        "wealth",
        "inheritance",
        "family legacy",
        "old money",
        "tradition",
        "financial security",
        "accomplishment",
        "stability",
        "established",
        "ancestry",
        "long-term success",
        "contribution",
        "affluence",
        "permanent",
        "solid foundations",
        "conventionality",
        "dynasty",
        "material abundance",
        "family business",
        "retirement",
        "generations",
        "culmination",
        "lasting success",
        "prosperity"
    ]
};