export const orixasDetail = {
    "Exu": {
        "name": "Exu",
        "coreIntentions": "opportunity, clarity, progress, communication, courage",
        "coreEssence": "Opens blocked paths",
        "displayName": "Orixá Exu",
        "meaning": "This sacred messenger dances at every crossroads, proving that communication is creation's first act. He opens pathways between worlds—teaching that movement itself is prayer, and every choice we make reshapes destiny's map.",
        "number": 0,
        "title": "Master of Sacred Openings",
        "coreMeaning": "New Paths — Divine Communication, Life Force Movement, and Choice Power",
        "keywords": [
            "beginning",
            "innocence",
            "spontaneity",
            "free spirit",
            "adventure",
            "journey",
            "leap of faith",
            "new start",
            "fresh",
            "naive",
            "optimistic",
            "carefree",
            "risk",
            "potential",
            "youth",
            "inexperience",
            "originality",
            "freedom",
            "wanderer",
            "trust",
            "courage",
            "unknown",
            "foolish",
            "playful",
            "curious",
            "openness",
            "wonder",
            "possibilities",
            "fearless",
            "childlike",
            "pure"
        ]
    },
    "Ogum": {
        "name": "Ogum",
        "coreIntentions": "courage, victory, protection, strength, breakthrough",
        "coreEssence": "Breaks through barriers",
        "displayName": "Orixá Ogum",
        "meaning": "This forge master transforms raw will into tempered action, his hammer striking sparks of possibility from the iron of determination. He represents breakthrough power—teaching that obstacles exist to reveal our capacity to cut through any limitation.",
        "number": 1,
        "title": "The Divine Blacksmith",
        "coreMeaning": "Breakthrough — Warrior Strength, Technology of Spirit, and Path Clearing",
        "keywords": [
            "manifestation",
            "power",
            "skill",
            "concentration",
            "action",
            "resourcefulness",
            "willpower",
            "creation",
            "ability",
            "talent",
            "transformation",
            "focus",
            "confidence",
            "mastery",
            "will",
            "divine tools",
            "magic",
            "alchemy",
            "intention",
            "conscious",
            "awareness",
            "control",
            "capability",
            "competence",
            "achievement",
            "realization",
            "potential",
            "initiative",
            "determination"
        ]
    },
    "Oxóssi": {
        "name": "Oxóssi",
        "coreIntentions": "abundance, focus, justice, persistence, clarity",
        "coreEssence": "Helps you find what you're looking for",
        "displayName": "Orixá Oxóssi",
        "meaning": "This forest king's single arrow never misses because he aims from perfect stillness, teaching that abundance comes to those who know precisely what they seek. He represents focused intention—showing that the universe provides when we clarify our true target.",
        "number": 2,
        "title": "The One-Arrow Master",
        "coreMeaning": "Precision — Focused Abundance, Sacred Hunt, and Provision Mastery",
        "keywords": [
            "intuition",
            "mystery",
            "subconscious",
            "higher power",
            "wisdom",
            "secrets",
            "inner voice",
            "unconscious",
            "divine feminine",
            "spirituality",
            "sacred knowledge",
            "psychic",
            "dreams",
            "hidden",
            "receptive",
            "passive",
            "stillness",
            "meditation",
            "lunar",
            "mystical",
            "esoteric",
            "veiled",
            "inner knowing",
            "patience",
            "silence",
            "duality",
            "guardian",
            "threshold"
        ]
    },
    "Omolu": {
        "name": "Omolu",
        "coreIntentions": "healing, transformation, protection, renewal, cleansing",
        "coreEssence": "Transforms suffering into wisdom",
        "displayName": "Orixá Omolu",
        "meaning": "This medicine keeper wears raffia to veil his transformation of poison into cure, shadow into light. He represents healing wisdom—teaching that our deepest wounds become our most powerful medicines when embraced with courage.",
        "number": 3,
        "title": "Master of Hidden Medicine",
        "coreMeaning": "Transformation — Disease to Cure, Shadow Integration, and Rebirth Power",
        "keywords": [
            "fertility",
            "abundance",
            "motherhood",
            "nature",
            "nurturing",
            "creativity",
            "beauty",
            "femininity",
            "luxury",
            "sensuality",
            "harvest",
            "pregnancy",
            "material wealth",
            "comfort",
            "earthly pleasures",
            "growth",
            "nourishment",
            "maternal",
            "venus",
            "love",
            "harmony",
            "receptivity",
            "compassion",
            "unconditional love",
            "divine feminine",
            "creation",
            "birth",
            "prosperity"
        ]
    },
    "Oxumaré": {
        "name": "Oxumaré",
        "coreIntentions": "prosperity, continuity, renewal, movement, abundance",
        "coreEssence": "Rainbow blessings",
        "displayName": "Orixá Oxumaré",
        "meaning": "This rainbow serpent bridges earth and sky in eternal movement, proving that duality is dance, not division. They represent cyclical wisdom—teaching that apparent opposites are partners in creation's endless spiral.",
        "number": 4,
        "title": "The Rainbow Bridge",
        "coreMeaning": "Integration — Sacred Cycles, Unity in Duality, and Eternal Movement",
        "keywords": [
            "authority",
            "structure",
            "control",
            "father figure",
            "leadership",
            "stability",
            "power",
            "protection",
            "discipline",
            "provider",
            "establishment",
            "logic",
            "foundation",
            "order",
            "masculine",
            "rules",
            "boundaries",
            "strategy",
            "ambition",
            "rational",
            "government",
            "law",
            "tradition",
            "security",
            "dominance",
            "achievement",
            "material success",
            "sovereignty"
        ]
    },
    "Xangô": {
        "name": "Xangô",
        "coreIntentions": "justice, power, truth, leadership, fairness",
        "coreEssence": "Brings justice and balance",
        "displayName": "Orixá Xangô",
        "meaning": "This thunder king's axe splits injustice with divine precision, his dance making the earth tremble with truth's power. He represents righteous authority—teaching that true leadership serves justice with both fierce love and joyful strength.",
        "number": 5,
        "title": "Lord of Sacred Thunder",
        "coreMeaning": "Justice — Divine Authority, Truth's Power, and Passionate Leadership",
        "keywords": [
            "tradition",
            "conformity",
            "institution",
            "education",
            "belief system",
            "spiritual wisdom",
            "religious",
            "ceremony",
            "conventional",
            "mentor",
            "teaching",
            "orthodoxy",
            "marriage",
            "commitment",
            "society",
            "approval",
            "tradition",
            "moral",
            "ethics",
            "values",
            "doctrine",
            "dogma",
            "ritual",
            "sacred",
            "guidance",
            "counsel",
            "established order",
            "spiritual authority"
        ]
    },
    "Oxalá": {
        "name": "Oxalá",
        "coreIntentions": "peace, clarity, wisdom, patience, creation",
        "coreEssence": "Brings peace and clarity",
        "displayName": "Orixá Oxalá",
        "meaning": "This ancient creator shapes consciousness like white cloth, each fold a universe of possibility wrapped in pristine peace. He represents original wisdom—teaching that true power whispers, and creation happens in the silence before the first breath.",
        "number": 6,
        "title": "The White-Robed Creator",
        "coreMeaning": "Wisdom — Pure Creation, Ancient Peace, and Patient Power",
        "keywords": [
            "love",
            "relationships",
            "choices",
            "alignment",
            "values",
            "partnership",
            "union",
            "attraction",
            "harmony",
            "soulmate",
            "romance",
            "sexuality",
            "passion",
            "desire",
            "commitment",
            "communication",
            "duality",
            "balance",
            "decisions",
            "crossroads",
            "temptation",
            "free will",
            "personal beliefs",
            "moral choices",
            "connection",
            "intimacy",
            "trust",
            "vulnerability"
        ]
    },
    "Oyá": {
        "name": "Oyá",
        "coreIntentions": "change, courage, transformation, strength, clarity",
        "coreEssence": "Clears away what no longer serves",
        "displayName": "Orixá Oyá",
        "meaning": "This wind mother commands nine winds of change, her storms clearing stagnant air for fresh possibilities. She represents transformation power—teaching that destruction and creation are lovers in the dance of becoming.",
        "number": 7,
        "title": "Mistress of Nine Winds",
        "coreMeaning": "Change — Sacred Storms, Ancestral Wisdom, and Transformation Dance",
        "keywords": [
            "control",
            "willpower",
            "determination",
            "success",
            "ambition",
            "focus",
            "victory",
            "assertion",
            "direction",
            "self-discipline",
            "confidence",
            "conquest",
            "overcoming",
            "hard work",
            "triumph",
            "journey",
            "progress",
            "warrior",
            "vehicle",
            "mastery",
            "drive",
            "momentum",
            "opposing forces",
            "balance",
            "swift action",
            "achievement",
            "perseverance",
            "courage"
        ]
    },
    "Iemanjá": {
        "name": "Iemanjá",
        "coreIntentions": "protection, nurturing, emotional healing, safety, comfort",
        "coreEssence": "Nurtures and protects",
        "displayName": "Orixá Iemanjá",
        "meaning": "This ocean mother rocks all life in her vast embrace, her depths holding both treasures and mysteries. She represents nurturing wisdom—teaching that true mothering means knowing when to hold close and when to release to the tide.",
        "number": 8,
        "title": "Mother of All Waters",
        "coreMeaning": "Nurturing — Protective Love, Emotional Depths, and Maternal Wisdom",
        "keywords": [
            "strength",
            "courage",
            "patience",
            "compassion",
            "control",
            "inner strength",
            "gentle power",
            "persuasion",
            "influence",
            "taming",
            "confidence",
            "self-control",
            "determination",
            "fortitude",
            "resilience",
            "endurance",
            "heart over mind",
            "soft control",
            "feminine power",
            "grace under pressure",
            "moral courage",
            "kindness",
            "understanding",
            "forgiveness",
            "healing",
            "integration",
            "beast taming",
            "raw power"
        ]
    },
    "Nanã": {
        "name": "Nanã",
        "coreIntentions": "wisdom, acceptance, patience, understanding, serenity",
        "coreEssence": "Teaches patience and acceptance",
        "displayName": "Orixá Nanã",
        "meaning": "This ancient grandmother holds the primordial mud from which all life emerged and returns, her wisdom predating time itself. She represents ancestral knowledge—teaching that some truths are too old for words, living instead in our bones.",
        "number": 9,
        "title": "Keeper of Primordial Wisdom",
        "coreMeaning": "Ancestry — Ancient Knowledge, Death Wisdom, and Primal Memory",
        "keywords": [
            "solitude",
            "introspection",
            "guidance",
            "wisdom",
            "inner light",
            "soul searching",
            "meditation",
            "self-discovery",
            "contemplation",
            "isolation",
            "withdrawal",
            "prudence",
            "discretion",
            "seeking",
            "spiritual quest",
            "inner voice",
            "teacher",
            "mentor",
            "enlightenment",
            "truth seeking",
            "patience",
            "inner journey",
            "reflection",
            "philosophy",
            "maturity",
            "experience",
            "lantern",
            "illumination"
        ]
    },
    "Obá": {
        "name": "Obá",
        "coreIntentions": "strength, loyalty, perseverance, dignity, courage",
        "coreEssence": "Stands firm in your truth",
        "displayName": "Orixá Obá",
        "meaning": "This warrior queen transforms sacrifice into strength, her story teaching that what seems like loss often reveals our hidden power. She represents fierce loyalty—showing that true love sometimes means fighting for your own worth.",
        "number": 10,
        "title": "The Sacrificial Warrior",
        "coreMeaning": "Strength — Sacred Sacrifice, Hidden Power, and Self-Worth",
        "keywords": [
            "cycles",
            "change",
            "fate",
            "luck",
            "fortune",
            "karma",
            "turning point",
            "destiny",
            "opportunities",
            "life cycles",
            "ups and downs",
            "movement",
            "chance",
            "synchronicity",
            "pivotal moment",
            "evolution",
            "progress",
            "seasons",
            "time",
            "revolution",
            "unexpected",
            "gambling",
            "risk",
            "wheel turning",
            "cosmic forces",
            "divine timing",
            "breakthrough",
            "fortune's wheel"
        ]
    },
    "Oxum": {
        "name": "Oxum",
        "coreIntentions": "love, fertility, prosperity, beauty, kindness",
        "coreEssence": "Attracts love and abundance",
        "displayName": "Orixá Oxum",
        "meaning": "This river goddess flows with liquid gold, her mirror reflecting beauty in all beings while her honey sweetens life's bitter moments. She represents sensual wisdom—teaching that pleasure and prosperity are birthrights, not privileges.",
        "number": 11,
        "title": "Lady of Sweet Waters",
        "coreMeaning": "Sweetness — Sensual Wisdom, Golden Abundance, and Self-Love",
        "keywords": [
            "justice",
            "fairness",
            "truth",
            "law",
            "balance",
            "accountability",
            "karma",
            "cause and effect",
            "integrity",
            "honesty",
            "responsibility",
            "legal matters",
            "decision",
            "impartiality",
            "objectivity",
            "ethics",
            "consequences",
            "clarity",
            "court",
            "judgment",
            "equilibrium",
            "scales",
            "sword",
            "divine justice",
            "moral law",
            "righteousness",
            "adjustment",
            "correction"
        ]
    },
    "Logunedé": {
        "name": "Logunedé",
        "coreIntentions": "balance, harmony, beauty, abundance, versatility",
        "coreEssence": "Harmonizes opposites",
        "displayName": "Orixá Logunedé",
        "meaning": "This divine youth dances between river and forest, embodying the grace of inhabiting multiple worlds without choosing sides. They represent fluid identity—teaching that wholeness comes from honoring all aspects of self.",
        "number": 12,
        "title": "Prince of Two Worlds",
        "coreMeaning": "Fluidity — Dual Nature, Youthful Wisdom, and Identity Dance",
        "keywords": [
            "sacrifice",
            "suspension",
            "letting go",
            "surrender",
            "new perspective",
            "waiting",
            "patience",
            "martyrdom",
            "release",
            "reversal",
            "contemplation",
            "limbo",
            "transition",
            "paradox",
            "enlightenment",
            "different viewpoint",
            "pause",
            "spiritual growth",
            "wisdom",
            "trials",
            "selflessness",
            "metamorphosis",
            "breaking patterns",
            "seeing differently",
            "voluntary sacrifice",
            "divine perspective",
            "illumination",
            "rebirth pending"
        ]
    },
    "Ibeji": {
        "name": "Ibeji",
        "coreIntentions": "joy, playfulness, protection, innocence, laughter",
        "coreEssence": "Restores joy and innocence",
        "displayName": "Orixá Ibeji",
        "meaning": "These sacred twins remind us that joy doubles when shared and sorrow halves when witnessed. They represent playful wisdom—teaching that the divine laughs through children and miracles hide in everyday moments.",
        "number": 13,
        "title": "The Sacred Twins",
        "coreMeaning": "Joy — Doubled Blessings, Inner Child, and Miraculous Play",
        "keywords": [
            "transformation",
            "endings",
            "beginnings",
            "change",
            "transition",
            "release",
            "metamorphosis",
            "rebirth",
            "renewal",
            "regeneration",
            "cycles",
            "mortality",
            "letting go",
            "severance",
            "conclusion",
            "closure",
            "elimination",
            "inevitable change",
            "profound change",
            "phoenix",
            "resurrection",
            "clearing",
            "purging",
            "evolution",
            "revolution",
            "death and rebirth",
            "major transition",
            "transformation"
        ]
    },
    "Ossaim": {
        "name": "Ossaim",
        "coreIntentions": "healing, remedy, wisdom, connection, secrets",
        "coreEssence": "Heals through nature's wisdom",
        "displayName": "Orixá Ossaim",
        "meaning": "This one-legged forest sage guards nature's pharmacy, knowing which leaf cures and which teaches through challenge. He represents natural wisdom—showing that healing grows wild for those who learn nature's secret language.",
        "number": 14,
        "title": "Guardian of Green Mysteries",
        "coreMeaning": "Natural Healing — Plant Wisdom, Sacred Medicine, and Earth Connection",
        "keywords": [
            "balance",
            "moderation",
            "patience",
            "harmony",
            "alchemy",
            "healing",
            "integration",
            "middle path",
            "compromise",
            "peace",
            "tranquility",
            "adaptation",
            "coordination",
            "tempering",
            "blending",
            "synthesis",
            "equilibrium",
            "purpose",
            "meaning",
            "flow",
            "divine connection",
            "guardian angel",
            "higher learning",
            "philosophy",
            "fusion",
            "unification",
            "patience",
            "art"
        ]
    },
    "Orunmilá": {
        "name": "Orunmilá",
        "coreIntentions": "clarity, destiny, guidance, wisdom, truth",
        "coreEssence": "Divine wisdom",
        "displayName": "Orixá Orunmilá",
        "meaning": "This witness of creation holds the map of all possible destinies, teaching that fate and free will dance together. He represents divine wisdom—showing that knowing your path and walking it are different initiations.",
        "number": 15,
        "title": "Master of Sacred Patterns",
        "coreMeaning": "Destiny — Divine Patterns, Choice Within Fate, and Wisdom Paths",
        "keywords": [
            "bondage",
            "addiction",
            "sexuality",
            "materialism",
            "attachment",
            "restriction",
            "temptation",
            "shadow self",
            "obsession",
            "dependency",
            "illusion",
            "oppression",
            "powerlessness",
            "fear",
            "ignorance",
            "hopelessness",
            "violence",
            "chains",
            "vices",
            "excess",
            "enslavement",
            "lust",
            "earthly pleasure",
            "hedonism",
            "manipulation",
            "control",
            "darkness",
            "raw desire"
        ]
    },
    "Iroko": {
        "name": "Iroko",
        "coreIntentions": "stability, longevity, roots, ancestors, patience",
        "coreEssence": "Sacred time",
        "displayName": "Orixá Iroko",
        "meaning": "This sacred tree connects heaven and earth through roots and branches, teaching that true strength comes from being grounded while reaching high. He represents stability—showing that flexibility and firmness create unshakeable presence.",
        "number": 16,
        "title": "The Time-Keeping Tree",
        "coreMeaning": "Stability — Deep Roots, Ancient Presence, and Flexible Strength",
        "keywords": [
            "destruction",
            "upheaval",
            "chaos",
            "revelation",
            "awakening",
            "breakdown",
            "liberation",
            "sudden change",
            "crisis",
            "release",
            "downfall",
            "exposure",
            "disaster",
            "shock",
            "disruption",
            "lightning bolt",
            "ego death",
            "breakthrough",
            "truth revealed",
            "collapse",
            "foundation shaking",
            "catastrophe",
            "enlightenment",
            "divine intervention",
            "rebuilding",
            "clearing",
            "purification",
            "forced change"
        ]
    },
    "Aganjú": {
        "name": "Aganjú",
        "coreIntentions": "independence, solitude, strength, power, wilderness",
        "coreEssence": "Volcanic power",
        "displayName": "Orixá Aganjú",
        "meaning": "This volcanic force demonstrates that sometimes creation requires eruption, that new land births from fire meeting water. He represents explosive potential—teaching that suppressed power eventually reshapes entire landscapes.",
        "number": 17,
        "title": "Lord of Inner Fire",
        "coreMeaning": "Eruption — Volcanic Power, Creative Destruction, and New Ground",
        "keywords": [
            "hope",
            "inspiration",
            "serenity",
            "healing",
            "renewal",
            "spirituality",
            "faith",
            "purpose",
            "guidance",
            "peace",
            "tranquility",
            "wishes",
            "optimism",
            "insight",
            "astronomy",
            "future",
            "calm",
            "free flowing",
            "blessings",
            "generosity",
            "water bearer",
            "aquarius",
            "wishes granted",
            "divine love",
            "protection",
            "good fortune",
            "spiritual guidance",
            "bright future"
        ]
    },
    "Onilé": {
        "name": "Onilé",
        "coreIntentions": "nature, stability, foundation, security, earth",
        "coreEssence": "Earth mother",
        "displayName": "Orixá Onilé",
        "meaning": "This earth mother literally grounds all existence, reminding us that every journey returns home to her embrace. She represents foundation—teaching that true power comes from knowing where you stand.",
        "number": 18,
        "title": "Owner of All Ground",
        "coreMeaning": "Foundation — Sacred Ground, True Home, and Earth Wisdom",
        "keywords": [
            "illusion",
            "intuition",
            "dreams",
            "subconscious",
            "fear",
            "anxiety",
            "deception",
            "confusion",
            "imagination",
            "mystery",
            "unconscious",
            "secrets",
            "shadow work",
            "psychic",
            "lunar cycles",
            "feminine",
            "emotions",
            "night",
            "hidden enemies",
            "insecurity",
            "dark night of soul",
            "uncertainty",
            "fluctuation",
            "reflection",
            "projection",
            "instinct",
            "madness",
            "howling"
        ]
    },
    "Ewá": {
        "name": "Ewá",
        "coreIntentions": "vision, clarity, beauty, purity, insight",
        "coreEssence": "Pure waters",
        "displayName": "Orixá Ewá",
        "meaning": "This mysterious beauty veils profound truths in ethereal grace, her enchantments teaching that some wisdom comes through wonder, not analysis. She represents mystical insight—showing that beauty itself is a form of truth.",
        "number": 19,
        "title": "Lady of Hidden Beauty",
        "coreMeaning": "Enchantment — Mystical Beauty, Veiled Wisdom, and Vision Gifts",
        "keywords": [
            "joy",
            "success",
            "vitality",
            "enlightenment",
            "warmth",
            "happiness",
            "positivity",
            "celebration",
            "achievement",
            "radiance",
            "energy",
            "life",
            "consciousness",
            "clarity",
            "confidence",
            "optimism",
            "enthusiasm",
            "childlike wonder",
            "playfulness",
            "growth",
            "abundance",
            "truth",
            "glory",
            "triumph",
            "illumination",
            "good fortune",
            "contentment",
            "brilliance"
        ]
    },
    "Olokun": {
        "name": "Olokun",
        "coreIntentions": "wealth, depth, revelation, abundance, treasures",
        "coreEssence": "Deep mysteries",
        "displayName": "Orixá Olokun",
        "meaning": "This keeper of ocean depths guards treasures and sorrows alike, teaching that the deepest riches require the deepest dives. They represent hidden wealth—showing that our greatest resources often lie in unexplored depths.",
        "number": 21,
        "title": "Sovereign of Hidden Depths",
        "coreMeaning": "Hidden Treasures — Deep Mysteries, Subconscious Wealth, and Secret Power",
        "keywords": [
            "completion",
            "accomplishment",
            "fulfillment",
            "wholeness",
            "achievement",
            "integration",
            "travel",
            "unity",
            "closure",
            "success",
            "realization",
            "enlightenment",
            "cosmic consciousness",
            "celebration",
            "synthesis",
            "graduation",
            "triumph",
            "perfection",
            "harmony",
            "world travel",
            "global awareness",
            "full circle",
            "totality",
            "cosmic dance",
            "mastery",
            "attainment",
            "universe",
            "infinite possibility"
        ]
    },
    "Ori": {
        "name": "Ori",
        "coreIntentions": "destiny, purpose, clarity, path, self-knowledge",
        "coreEssence": "Personal destiny",
        "displayName": "Orixá Ori",
        "meaning": "This inner head chose your destiny before birth, making you the living prayer of your highest self. Ori represents personal divinity—teaching that your truest guardian lives within, and alignment with inner wisdom surpasses all external forces.",
        "number": 22,
        "title": "Guardian of Personal Destiny",
        "coreMeaning": "Inner Authority — Personal Destiny, Self-Alignment, and Divine Identity",
        "keywords": [
            "inspiration",
            "new beginning",
            "creative spark",
            "potential",
            "passion",
            "enthusiasm",
            "initiative",
            "breakthrough",
            "opportunity",
            "courage",
            "growth",
            "birth",
            "innovation",
            "vitality",
            "fire energy",
            "divine spark",
            "motivation",
            "ambition",
            "raw power",
            "spontaneity",
            "spiritual gift",
            "awakening",
            "enterprise",
            "adventure"
        ]
    },
    "Egungun": {
        "name": "Egungun",
        "coreIntentions": "ancestors, guidance, protection, tradition, wisdom",
        "coreEssence": "Ancestral wisdom",
        "displayName": "Orixá Egungun",
        "meaning": "These ancestral voices speak through blood memory, proving that death merely transforms love into a different frequency. They represent living legacy—teaching that we stand on invisible shoulders and our actions ripple through generations.",
        "number": 23,
        "title": "Voices of the Eternal Family",
        "coreMeaning": "Legacy — Ancestral Wisdom, Blood Memory, and Eternal Connection",
    },
    "Ajé": {
        "name": "Ajé",
        "coreIntentions": "wealth, success, prosperity, abundance, opportunity",
        "coreEssence": "Prosperity flow",
        "displayName": "Orixá Ajé",
        "meaning": "This force of prosperity flows where value is recognized and exchanged with integrity. She represents wealth consciousness—teaching that abundance multiplies through circulation and that commerce can be sacred when it serves community.",
        "number": 24,
        "title": "Keeper of Sacred Exchange",
        "coreMeaning": "Wealth Flow — Prosperity Consciousness, Sacred Commerce, and Value Recognition",
    },
    "Oranyian": {
        "name": "Oranyian",
        "coreIntentions": "strength, foundation, leadership, courage, victory",
        "coreEssence": "United strength",
        "displayName": "Orixá Oranyian",
        "meaning": "This warrior prince united two kingdoms through courage and wisdom, proving that true nobility serves the collective. He represents heroic leadership—teaching that greatness emerges when personal glory surrenders to communal good.",
        "number": 25,
        "title": "The Unifying Prince",
        "coreMeaning": "Noble Action — Heroic Service, Unity Leadership, and Collective Strength",
    },
    "Yewa": {
        "name": "Yewa",
        "coreIntentions": "boundaries, protection, purity, respect, solitude",
        "coreEssence": "Sacred silence",
        "displayName": "Orixá Yewa",
        "meaning": "This virgin crone guards the space between death and rebirth, her purity not innocence but fierce protection of transformation. She represents sacred boundaries—teaching that some transformations require absolute solitude and uncompromising standards.",
        "number": 27,
        "title": "Keeper of Sacred Solitude",
        "coreMeaning": "Sacred Boundaries — Protective Solitude, Transformation Space, and Fierce Purity",
    },
    // "Obatalá Ayagunna": {
    //     "name": "Obatalá Ayagunna",
    //     "coreEssence": "Young warrior",
    //     "displayName": "Orixá Obatalá Ayagunna",
    //     "meaning": "This young warrior aspect of creation proves that even peace must sometimes fight for its existence. He represents righteous rebellion—teaching that creation includes the courage to destroy what dishonors the sacred.",
    //     "number": 30,
    //     "title": "The Young Lion of Light",
    //     "coreMeaning": "Sacred Rebellion — Youthful Courage, Creative Combat, and Pure Force",
    // },
    "Aroni": {
        "name": "Aroni",
        "coreIntentions": "wisdom, healing, nature, knowledge, answers",
        "coreEssence": "Forest wisdom",
        "displayName": "Orixá Aroni",
        "meaning": "This forest guardian with one leg and one arm knows every secret the green world whispers. He represents hidden knowledge—teaching that nature's deepest medicines reveal themselves only to those who approach with humble patience.",
        "number": 31,
        "title": "The Whispering Woods Keeper",
        "coreMeaning": "Secret Knowledge — Forest Mysteries, Patient Learning, and Natural Initiation",
    },
    // "Alafim": {
    //     "name": "Alafim",
    //     "coreEssence": "Royal grace",
    //     "displayName": "Orixá Alafim",
    //     "meaning": "This royal authority demonstrates that true power serves the people, not the throne. He represents divine governance—teaching that leadership is a sacred contract where the crown's weight equals its responsibility.",
    //     "number": 32,
    //     "title": "The People's Divine King",
    //     "coreMeaning": "Sacred Authority — Divine Leadership, Royal Service, and Power's Purpose",
    //     "keywords": [
    //         "messenger",
    //         "enthusiasm",
    //         "exploration",
    //         "discovery",
    //         "free spirit",
    //         "adventure",
    //         "courage",
    //         "excitement",
    //         "new ideas",
    //         "creative spark",
    //         "inspiration",
    //         "good news",
    //         "passionate",
    //         "eager",
    //         "playful",
    //         "spontaneous",
    //         "optimistic",
    //         "fearless",
    //         "student of fire",
    //         "youthful energy",
    //         "fresh start",
    //         "creative message",
    //         "potential",
    //         "impulsive"
    //     ]
    // },

    "Obaluayê": {
        "name": "Obaluayê",
        "coreIntentions": "healing, rebirth, recovery, earth, cleansing",
        "coreEssence": "Master healer",
        "displayName": "Orixá Obaluayê",
        "meaning": "This young, unveiled healer strides through the world with transformative fire, turning decay into renewal. As the active aspect of Omolu, he represents confronting illness with fierce visibility, teaching that healing begins when we no longer hide our wounds.",
        "number": 34,
        "title": "The Unmasked Healer",
        "coreMeaning": "Revealed Healing — Courageous Recovery, Visible Wounds, and Transformational Illness",
        "keywords": [
            "confident",
            "independent",
            "charismatic",
            "bold",
            "creative",
            "passionate",
            "warm",
            "vibrant",
            "courageous",
            "determined",
            "outgoing",
            "magnetic",
            "queen of fire",
            "optimistic",
            "friendly",
            "energetic",
            "inspiring",
            "generous",
            "wholehearted",
            "vivacious",
            "self-assured",
            "fertility",
            "leadership",
            "radiant"
        ]
    },

    "Egbe": {
        "name": "Egbe",
        "coreIntentions": "community, belonging, companionship, support, connection",
        "coreEssence": "Spirit companion",
        "displayName": "Orixá Egbe",
        "meaning": "These celestial spirit companions remind us that we are never fully alone, even in solitude. Egbe represents the soul’s parallel existence in the heavenly realm—teaching that alignment with our higher self reunites us with our cosmic twin.",
        "number": 35,
        "title": "The Celestial Mirror",
        "coreMeaning": "Spiritual Alignment — Cosmic Twinship, Soul Memory, and Inner Reunion",
        "keywords": [
            "natural leader",
            "visionary",
            "entrepreneur",
            "charismatic",
            "bold",
            "inspiring",
            "confident",
            "king of fire",
            "generous",
            "motivating",
            "influential",
            "commanding",
            "optimistic",
            "adventurous",
            "passionate leader",
            "courageous",
            "pioneering",
            "ambitious",
            "creative vision",
            "masterful",
            "noble",
            "expansive",
            "authoritative",
            "protective"
        ]
    },

    "Ibú": {
        "name": "Ibú",
        "coreIntentions": "kindness, flow, love, gentleness, grace",
        "coreEssence": "Many waters",
        "displayName": "Orixá Ibú",
        "meaning": "These feminine aspects of Iemanjá embody different tides, moods, and secrets of the ocean’s depths. Each avatar holds a unique flavor of maternal power—teaching that divine feminine expresses in infinite forms, not just one face.",
        "number": 36,
        "title": "Faces of the Deep",
        "coreMeaning": "Fluid Divinity — Feminine Multiplicity, Emotional Archetypes, and Water Power",
        "keywords": [
            "new love",
            "emotional beginning",
            "intuition",
            "spiritual awakening",
            "creativity",
            "compassion",
            "emotional release",
            "joy",
            "inner peace",
            "fertility",
            "new relationship",
            "forgiveness",
            "divine love",
            "emotional renewal",
            "happiness",
            "fulfillment",
            "abundance",
            "healing",
            "receptivity",
            "grace",
            "blessing",
            "emotional gift",
            "psychic opening",
            "heart opening"
        ]
    },

    "Orisha Oko": {
        "name": "Orisha Oko",
        "coreIntentions": "fruition, fertility, abundance, growth, contentment",
        "coreEssence": "Harvest abundance",
        "displayName": "Orixá Oko",
        "meaning": "This dignified farmer tills the spiritual soil, ensuring that justice and fertility go hand in hand. He represents grounded abundance—teaching that the harvest belongs to those who honor the land and labor with love.",
        "number": 37,
        "title": "Guardian of Sacred Agriculture",
        "coreMeaning": "Fertile Justice — Earth Wisdom, Righteous Harvest, and Grounded Prosperity",
        "keywords": [
            "partnership",
            "union",
            "love",
            "attraction",
            "connection",
            "relationships",
            "harmony",
            "balance",
            "mutual respect",
            "soulmate",
            "romance",
            "friendship",
            "equality",
            "proposal",
            "engagement",
            "truce",
            "cooperation",
            "healing",
            "reconciliation",
            "chemistry",
            "mutual attraction",
            "unified",
            "bond",
            "sacred union"
        ]
    }
}