export const symbolCards = {
    "Dawn": {"number": 0, "displayName": "Dawn", "tarot": "The Fool"},
    "Fire": {"number": 1, "displayName": "Fire", "tarot": "The Magician"},
    "River": {"number": 2, "displayName": "River", "tarot": "The High Priestess"},
    "Rain": {"number": 3, "displayName": "Rain", "tarot": "The Empress"},
    "Chair/Throne": {"number": 4, "displayName": "Chair/Throne", "tarot": "The Emperor"},
    "Temple": {"number": 5, "displayName": "Temple", "tarot": "The Hierophant"},
    "Eclipse": {"number": 6, "displayName": "Eclipse", "tarot": "The Lovers"},
    "Bow and Arrow": {"number": 7, "displayName": "Bow and Arrow", "tarot": "The Chariot"},
    "Great Cats": {"number": 8, "displayName": "Great Cats", "tarot": "Strength"},
    "Lamp/Candle": {"number": 9, "displayName": "Lamp/Candle", "tarot": "The Hermit"},
    "Mandala": {"number": 10, "displayName": "Mandala", "tarot": "Wheel of Fortune"},
    "Scale": {"number": 11, "displayName": "Scale", "tarot": "Justice"},
    "Tree": {"number": 12, "displayName": "Tree", "tarot": "The Hanged Man"},
    "Metamorphosis": {"number": 13, "displayName": "Metamorphosis", "tarot": "Death"},
    "Waterfall": {"number": 14, "displayName": "Waterfall", "tarot": "Temperance"},
    "Chain": {"number": 15, "displayName": "Chain", "tarot": "The Devil"},
    "Lightning": {"number": 16, "displayName": "Lightning", "tarot": "The Tower"},
    "Star": {"number": 17, "displayName": "Star", "tarot": "The Star"},
    "Moon": {"number": 18, "displayName": "Moon", "tarot": "The Moon"},
    "Sun": {"number": 19, "displayName": "Sun", "tarot": "The Sun"},
    "Trumpet/Horn": {"number": 20, "displayName": "Trumpet/Horn", "tarot": "Judgement"},
    "Wreath": {"number": 21, "displayName": "Wreath", "tarot": "The World"},

    "Chakras": {"number": 22, "displayName": "Chakras", "tarot": "Ace of Cups"},
    "Adam and Eve": {"number": 23, "displayName": "Adam and Eve", "tarot": "Two of Cups"},
    "Grape": {"number": 24, "displayName": "Grape", "tarot": "Three of Cups"},
    "Pool": {"number": 25, "displayName": "Pool", "tarot": "Four of Cups"},
    "Tears": {"number": 26, "displayName": "Tears", "tarot": "Five of Cups"},
    "Child": {"number": 27, "displayName": "Child", "tarot": "Six of Cups"},
    "Dream": {"number": 28, "displayName": "Dream", "tarot": "Seven of Cups"},
    "Path/Road": {"number": 29, "displayName": "Path/Road", "tarot": "Eight of Cups"},
    "Grail": {"number": 30, "displayName": "Grail", "tarot": "Nine of Cups"},
    "Rainbow": {"number": 31, "displayName": "Rainbow", "tarot": "Ten of Cups"},
    "Fish": {"number": 32, "displayName": "Fish", "tarot": "Page of Cups"},
    "Horse": {"number": 33, "displayName": "Horse", "tarot": "Knight of Cups"},
    "Well": {"number": 34, "displayName": "Well", "tarot": "Queen of Cups"},
    "Whale": {"number": 35, "displayName": "Whale", "tarot": "King of Cups"},

    "Spark": {"number": 36, "displayName": "Spark", "tarot": "Ace of Wands"},
    "Window": {"number": 37, "displayName": "Window", "tarot": "Two of Wands"},
    "Ship/Wreck": {"number": 38, "displayName": "Ship/Wreck", "tarot": "Three of Wands"},
    "House/Home": {"number": 39, "displayName": "House/Home", "tarot": "Four of Wands"},
    "War/Warrior": {"number": 40, "displayName": "War/Warrior", "tarot": "Five of Wands"},
    "Crown": {"number": 41, "displayName": "Crown", "tarot": "Six of Wands"},
    "Spear": {"number": 42, "displayName": "Spear", "tarot": "Seven of Wands"},
    "Wind": {"number": 43, "displayName": "Wind", "tarot": "Eight of Wands"},
    "Oak Tree": {"number": 44, "displayName": "Oak Tree", "tarot": "Nine of Wands"},
    "Basket": {"number": 45, "displayName": "Basket", "tarot": "Ten of Wands"},
    "Butterfly/Moth": {"number": 46, "displayName": "Butterfly/Moth", "tarot": "Page of Wands"},
    "Coyote": {"number": 47, "displayName": "Coyote", "tarot": "Knight of Wands"},
    "Peacock": {"number": 48, "displayName": "Peacock", "tarot": "Queen of Wands"},
    "Falcon": {"number": 49, "displayName": "Falcon", "tarot": "King of Wands"},

    "Sword": {"number": 50, "displayName": "Sword", "tarot": "Ace of Swords"},
    "Veil": {"number": 51, "displayName": "Veil", "tarot": "Two of Swords"},
    "Heart": {"number": 52, "displayName": "Heart", "tarot": "Three of Swords"},
    "Bed/Bedroom": {"number": 53, "displayName": "Bed/Bedroom", "tarot": "Four of Swords"},
    "Thief/Robber": {"number": 54, "displayName": "Thief/Robber", "tarot": "Five of Swords"},
    "Boat": {"number": 55, "displayName": "Boat", "tarot": "Six of Swords"},
    "Mask": {"number": 56, "displayName": "Mask", "tarot": "Seven of Swords"},
    "Prison": {"number": 57, "displayName": "Prison", "tarot": "Eight of Swords"},
    "Night": {"number": 58, "displayName": "Night", "tarot": "Nine of Swords"},
    "Burial": {"number": 59, "displayName": "Burial", "tarot": "Ten of Swords"},
    "Eye": {"number": 60, "displayName": "Eye", "tarot": "Page of Swords"},
    "Knife/Dagger": {"number": 61, "displayName": "Knife/Dagger", "tarot": "Knight of Swords"},
    "Mirror": {"number": 62, "displayName": "Mirror", "tarot": "Queen of Swords"},
    "Helmet": {"number": 63, "displayName": "Helmet", "tarot": "King of Swords"}

    "Seed": {"number": 64, "displayName": "Seed", "tarot": "Ace of Pentacles"},
    "Knot": {"number": 65, "displayName": "Knot", "tarot": "Two of Pentacles"},
    "Architect": {"number": 66, "displayName": "Architect", "tarot": "Three of Pentacles"},
    "Purse": {"number": 67, "displayName": "Purse", "tarot": "Four of Pentacles"},
    "Beggar": {"number": 68, "displayName": "Beggar", "tarot": "Five of Pentacles"},
    "Hand": {"number": 69, "displayName": "Hand", "tarot": "Six of Pentacles"},
    "Sowing": {"number": 70, "displayName": "Sowing", "tarot": "Seven of Pentacles"},
    "Hammer": {"number": 71, "displayName": "Hammer", "tarot": "Eight of Pentacles"},
    "Garden": {"number": 72, "displayName": "Garden", "tarot": "Nine of Pentacles"},
    "Ancestor": {"number": 73, "displayName": "Ancestor", "tarot": "Ten of Pentacles"},
    "Acorn": {"number": 74, "displayName": "Acorn", "tarot": "Page of Pentacles"},
    "Plow": {"number": 75, "displayName": "Plow", "tarot": "Knight of Pentacles"},
    "Hearth": {"number": 76, "displayName": "Hearth", "tarot": "Queen of Pentacles"},
    "Gold": {"number": 77, "displayName": "Gold", "tarot": "King of Pentacles"}
}