export const tarotCardsDetail = {
    "The Fool": {
        "name": "The Fool",
        "coreIntentions": "new beginnings, trusting process, releasing fear, innocent joy, fresh start",
        "meaning": "The Fool dances at the edge of possibility, reminding us that every master was once a beginner. This card invites you to trust the wild wisdom of not knowing, for it is in the space of innocence that miracles are born.",
        "number": 0,
        "title": "Sacred Leap into Mystery",
        "coreMeaning": "Beginning — Trust, Innocence, and the Courage to Not Know",
        "keywords": [
            "breath",
            "beginning",
            "innocence",
            "spontaneity",
            "free spirit",
            "adventure",
            "journey",
            "leap of faith",
            "new start",
            "fresh",
            "naive",
            "optimistic",
            "carefree",
            "risk",
            "potential",
            "youth",
            "inexperience",
            "originality",
            "freedom",
            "wanderer",
            "trust",
            "courage",
            "unknown",
            "foolish",
            "playful",
            "curious",
            "openness",
            "wonder",
            "possibilities",
            "fearless",
            "childlike",
            "pure"
        ],
    },
    "The Magician": {
        "name": "The Magician",
        "coreIntentions": "manifesting desires, focused intention, personal power, creating reality, divine will",
        "meaning": "The Magician stands as the bridge between heaven and earth, wielding the four elements with conscious intention. You hold the cosmic toolkit—now is the time to alchemize your dreams into reality through focused will.",
        "number": 1,
        "title": "Weaver of Worlds",
        "coreMeaning": "Manifestation — Will, Focus, and Divine Tools",
        "keywords": [
            "manifestation",
            "power",
            "skill",
            "concentration",
            "action",
            "resourcefulness",
            "willpower",
            "creation",
            "ability",
            "talent",
            "transformation",
            "focus",
            "confidence",
            "mastery",
            "will",
            "divine tools",
            "magic",
            "alchemy",
            "intention",
            "conscious",
            "awareness",
            "control",
            "capability",
            "competence",
            "achievement",
            "realization",
            "potential",
            "initiative",
            "determination"
        ],
    },
    "The High Priestess": {
        "name": "The High Priestess",
        "coreIntentions": "inner wisdom, trusting intuition, hidden knowledge, sacred mysteries, quiet knowing",
        "meaning": "The High Priestess guards the threshold between worlds, keeper of mysteries that cannot be spoken, only known. She invites you to silence the noise and listen to the ancient wisdom that flows through your intuitive channels.",
        "number": 2,
        "title": "Guardian of the Veil",
        "coreMeaning": "Intuition — Mystery, Inner Knowing, and Sacred Silence",
        "keywords": [
            "awareness",
            "intuition",
            "mystery",
            "subconscious",
            "higher power",
            "wisdom",
            "secrets",
            "meditation",
            "spirituality",
            "inner voice",
            "divine feminine",
            "psychic",
            "dreams",
            "hidden",
            "moon",
            "receptive",
            "inner knowing",
            "sacred silence",
            "mystical",
            "unconscious",
            "veil",
            "duality",
            "patience",
            "stillness",
            "contemplation",
            "reflection",
            "insight",
            "perception",
            "awareness"
        ],
    },
    "The Empress": {
        "name": "The Empress",
        "coreIntentions": "creative abundance, self nurturing, fertile ground, natural flow, motherly comfort",
        "meaning": "The Empress embodies creation itself—lush, sensual, and endlessly abundant. She reminds you that you are nature, not separate from it, and your creative power flows as naturally as rivers to the sea.",
        "number": 3,
        "title": "Mother of Infinite Gardens",
        "coreMeaning": "Abundance — Creation, Nurturing, and Sensual Power",
        "keywords": [
            "fertility",
            "femininity",
            "beauty",
            "nature",
            "abundance",
            "nurturing",
            "creation",
            "mother",
            "pregnancy",
            "comfort",
            "sensuality",
            "love",
            "harmony",
            "luxury",
            "garden",
            "venus",
            "life",
            "birth",
            "growth",
            "motherhood",
            "compassion",
            "creativity",
            "pleasure",
            "prosperity",
            "nourishment",
            "care",
            "warmth",
            "generosity",
            "receptivity"
        ],
    },
    "The Emperor": {
        "name": "The Emperor",
        "coreIntentions": "stable foundation, healthy boundaries, taking charge, structured growth, protective strength",
        "meaning": "The Emperor transforms chaos into cosmos through the sacred architecture of order. He teaches that true authority comes not from dominance but from the wisdom to create structures that support life's flourishing.",
        "number": 4,
        "title": "Architect of Sacred Order",
        "coreMeaning": "Authority — Structure, Leadership, and Protective Power",
        "keywords": [
            "authority",
            "structure",
            "control",
            "father",
            "leadership",
            "stability",
            "power",
            "rules",
            "discipline",
            "protection",
            "provider",
            "logic",
            "order",
            "government",
            "masculine",
            "protective power",
            "foundation",
            "security",
            "tradition",
            "establishment",
            "dominance",
            "responsibility",
            "boundaries",
            "organization",
            "strategy",
            "command",
            "sovereignty"
        ],
    },
    "The Hierophant": {
        "name": "The Hierophant",
        "coreIntentions": "spiritual guidance, seeking wisdom, traditional values, finding teachers, sacred learning",
        "meaning": "The Hierophant bridges the eternal and temporal, translating cosmic law into human understanding. This teacher appears when you're ready to understand the deeper patterns that govern both tradition and transformation.",
        "number": 5,
        "title": "Keeper of Sacred Keys",
        "coreMeaning": "Tradition — Teaching, Spiritual Systems, and Sacred Knowledge",
        "keywords": [
            "tradition",
            "conformity",
            "religion",
            "beliefs",
            "education",
            "knowledge",
            "teacher",
            "institutions",
            "ceremony",
            "ritual",
            "marriage",
            "commitment",
            "spiritual wisdom",
            "mentor",
            "teaching",
            "spiritual systems",
            "sacred knowledge",
            "orthodoxy",
            "convention",
            "guidance",
            "counsel",
            "doctrine",
            "faith",
            "blessing",
            "initiation",
            "hierarchy",
            "community",
            "belonging"
        ],
    },
    "The Lovers": {
        "name": "The Lovers",
        "coreIntentions": "conscious choice, soul connection, harmonious union, relationship healing, authentic love",
        "meaning": "The Lovers reflect the divine union possible when we choose from the deepest truth of our being. This is the alchemy of conscious choice—where two become one while remaining beautifully, distinctly themselves.",
        "number": 6,
        "title": "Mirror of Sacred Choice",
        "coreMeaning": "Union — Choice, Harmony, and Divine Partnership",
        "keywords": [
            "love",
            "harmony",
            "relationships",
            "values",
            "choices",
            "romance",
            "union",
            "attraction",
            "beauty",
            "trials",
            "duality",
            "passion",
            "sexuality",
            "connection",
            "partnership",
            "choice",
            "divine partnership",
            "commitment",
            "trust",
            "communication",
            "balance",
            "soul mate",
            "chemistry",
            "desire",
            "temptation",
            "alignment",
            "unity"
        ],
    },
    "The Chariot": {
        "name": "The Chariot",
        "coreIntentions": "inner victory, forward movement, overcoming obstacles, determined progress, self mastery",
        "meaning": "The Chariot masters the art of aligned momentum, harnessing opposing forces into unified direction. Victory comes not from suppressing contradictions but from making them dance together toward your destination.",
        "number": 7,
        "title": "Master of Aligned Forces",
        "coreMeaning": "Victory — Will, Direction, and Controlled Power",
        "keywords": [
            "control",
            "willpower",
            "success",
            "determination",
            "speed",
            "ambition",
            "confidence",
            "victory",
            "assertion",
            "direction",
            "travel",
            "progression",
            "warrior",
            "triumph",
            "will",
            "controlled power",
            "momentum",
            "drive",
            "conquest",
            "overcoming",
            "discipline",
            "focus",
            "journey",
            "vehicle",
            "mastery",
            "achievement",
            "forward movement",
            "perseverance"
        ],
    },

    "Strength": {
        "name": "Strength",
        "coreIntentions": "gentle strength, patient courage, inner power, taming fear, compassionate force",
        "meaning": "Strength reveals the invincible power of gentleness, where the lion of our primal nature is tamed not by force but by infinite patience and love. Here, vulnerability becomes your greatest armor.",
        "number": 8,
        "title": "The Gentle Conquerer",
        "coreMeaning": "Courage — Compassion, Inner Power, and Patient Love",
        "keywords": [
            "strength",
            "courage",
            "patience",
            "control",
            "compassion",
            "focus",
            "confidence",
            "inner strength",
            "gentle",
            "soft control",
            "taming",
            "fortitude",
            "resolve",
            "influence",
            "inner power",
            "patient love",
            "bravery",
            "endurance",
            "persistence",
            "calm",
            "self-control",
            "persuasion",
            "determination",
            "resilience",
            "grace",
            "kindness"
        ],
    },

    "The Hermit": {
        "name": "The Hermit",
        "coreIntentions": "soul searching, inner guidance, solitary wisdom, deep reflection, finding answers",
        "meaning": "The Hermit withdraws not from life but deeper into it, carrying a lantern lit by inner knowing. In sacred solitude, you discover that the teacher you've been seeking has been within you all along.",
        "number": 9,
        "title": "Keeper of Inner Light",
        "coreMeaning": "Solitude — Inner Guidance, Wisdom, and Sacred Withdrawal",
        "keywords": [
            "introspection",
            "solitude",
            "guidance",
            "wisdom",
            "truth",
            "inner guidance",
            "contemplation",
            "searching",
            "meditation",
            "isolation",
            "prudence",
            "teacher",
            "withdrawal",
            "sacred withdrawal",
            "loneliness",
            "soul searching",
            "enlightenment",
            "inner light",
            "seeking",
            "reflection",
            "spiritual quest",
            "mentor",
            "sage",
            "ascetic",
            "philosophy",
            "understanding"
        ],
    },
    "Wheel of Fortune": {
        "name": "Wheel of Fortune",
        "coreIntentions": "life cycles, turning point, divine timing, accepting change, karmic lessons",
        "meaning": "The Wheel of Fortune spins the cosmic web where fate and free will dance as partners. This turning point reminds you that while you cannot control the wheel's movement, you can choose how you ride its rhythms.",
        "number": 10,
        "title": "The Cosmic Spinner",
        "coreMeaning": "Cycles — Change, Destiny, and Divine Timing",
        "keywords": [
            "seasons",
            "luck",
            "karma",
            "fate",
            "destiny",
            "fortune",
            "cycles",
            "change",
            "ups and downs",
            "chance",
            "turning point",
            "opportunity",
            "expansion",
            "vision",
            "randomness",
            "divine timing",
            "wheel",
            "rotation",
            "inevitability",
            "providence",
            "serendipity",
            "reversal",
            "evolution",
            "progress",
            "circumstances",
            "pivot",
            "flux",
            "rhythm",
            "seasons"
        ],
    },
    "Justice": {
        "name": "Justice",
        "coreIntentions": "fair outcome, balanced decision, truth revealed, karmic justice, clear judgment",
        "meaning": "Justice wields the sword of truth and the scales of cosmic law, revealing that every action ripples through eternity. This is the profound balance where mercy and accountability create true harmony.",
        "number": 11,
        "title": "Keeper of Cosmic Balance",
        "coreMeaning": "Truth — Balance, Fairness, and Divine Law",
        "keywords": [
            "justice",
            "fairness",
            "truth",
            "law",
            "balance",
            "responsibility",
            "decision",
            "cause and effect",
            "integrity",
            "accountability",
            "honesty",
            "equality",
            "righteousness",
            "divine law",
            "karma",
            "judgment",
            "clarity",
            "objectivity",
            "analysis",
            "court",
            "legal",
            "ethics",
            "morality",
            "consequences",
            "impartiality",
            "reason",
            "logic",
            "weighing"
        ],
    },
    "The Hanged Man": {
        "name": "The Hanged Man",
        "coreIntentions": "sacred pause, new perspective, letting go, willing surrender, spiritual insight",
        "meaning": "The Hanged Man discovers enlightenment through sacred pause, finding wisdom in the space between breaths. By surrendering the need to move forward, you unlock perspectives invisible to those who rush.",
        "number": 12,
        "title": "Master of Sacred Suspension",
        "coreMeaning": "Surrender — New Perspective, Pause, and Willing Sacrifice",
        "keywords": [
            "stillness",
            "suspension",
            "letting go",
            "surrender",
            "sacrifice",
            "perspective",
            "waiting",
            "uncertainty",
            "contemplation",
            "transition",
            "paradox",
            "patience",
            "enlightenment",
            "new perspective",
            "pause",
            "willing sacrifice",
            "release",
            "martyrdom",
            "limbo",
            "stasis",
            "reversal",
            "different viewpoint",
            "wisdom",
            "spiritual growth",
            "acceptance",
            "trust",
            "faith"
        ],
    },
    "Death": {
        "name": "Death",
        "coreIntentions": "transformation time, necessary ending, phoenix rising, profound change, rebirth ready",
        "meaning": "Death arrives not as ending but as sacred transformation, clearing space for what's waiting to be born. This is the ultimate liberation—releasing form to discover the immortal essence that you truly are.",
        "number": 13,
        "title": "The Sacred Transformer",
        "coreMeaning": "Transformation — Endings, Rebirth, and Profound Change",
        "keywords": [
            "impermanence",
            "ending",
            "transformation",
            "transition",
            "change",
            "rebirth",
            "renewal",
            "release",
            "letting go",
            "cycles",
            "metamorphosis",
            "closure",
            "inevitable",
            "regeneration",
            "profound change",
            "mortality",
            "finality",
            "severance",
            "purging",
            "cleansing",
            "phoenix",
            "resurrection",
            "evolution",
            "liberation",
            "clearing",
            "void",
            "threshold",
            "passage"
        ],
    },
    "Temperance": {
        "name": "Temperance",
        "coreIntentions": "finding balance, patient healing, middle path, gentle blending, inner harmony",
        "meaning": "Temperance pours the golden elixir of balance, blending opposites into a third, transcendent possibility. This is the art of sacred alchemy—finding the perfect measure that transforms lead into gold.",
        "number": 14,
        "title": "The Divine Alchemist",
        "coreMeaning": "Balance — Integration, Patience, and Sacred Blending",
        "keywords": [
            "forgiveness",
            "balance",
            "moderation",
            "patience",
            "purpose",
            "peace",
            "tranquility",
            "harmony",
            "healing",
            "alchemy",
            "blending",
            "middle path",
            "calm",
            "adaptation",
            "integration",
            "sacred blending",
            "equilibrium",
            "synthesis",
            "compromise",
            "cooperation",
            "diplomacy",
            "fusion",
            "mixture",
            "tempering",
            "adjustment",
            "flow",
            "grace",
            "serenity"
        ],
    },
    "The Devil": {
        "name": "The Devil",
        "coreIntentions": "breaking chains, releasing addiction, shadow work, seeing clearly, liberation calling",
        "meaning": "The Devil illuminates the chains we forge from our own fears and desires, revealing that every prison has a door we've forgotten we can open. Liberation begins the moment you remember you hold the key.",
        "number": 15,
        "title": "Teacher of Hidden Freedom",
        "coreMeaning": "Bondage — Illusion, Attachment, and Hidden Liberation",
        "keywords": [
            "bondage",
            "addiction",
            "temptation",
            "materialism",
            "sexuality",
            "attachment",
            "restriction",
            "fear",
            "shadow",
            "obsession",
            "excess",
            "powerlessness",
            "illusion",
            "hidden liberation",
            "chains",
            "enslavement",
            "vice",
            "ignorance",
            "hopelessness",
            "oppression",
            "hedonism",
            "corruption",
            "negativity",
            "toxic",
            "trapped",
            "darkness"
        ],
    },
    "The Tower": {
        "name": "The Tower",
        "coreIntentions": "sudden breakthrough, divine disruption, tower falling, truth explosion, forced awakening",
        "meaning": "The Tower brings lightning revelation that shatters false foundations, freeing you from prisons you didn't know you inhabited. This divine disruption clears the way for authentic reconstruction on solid ground.",
        "number": 16,
        "title": "Lightning of Liberation",
        "coreMeaning": "Revelation — Sudden Change, Awakening, and Divine Disruption",
        "keywords": [
            "letting go",
            "destruction",
            "upheaval",
            "chaos",
            "revelation",
            "awakening",
            "breakdown",
            "liberation",
            "sudden change",
            "disaster",
            "crisis",
            "release",
            "truth",
            "shock",
            "divine disruption",
            "lightning",
            "collapse",
            "catastrophe",
            "breakthrough",
            "demolition",
            "explosion",
            "trauma",
            "emergency",
            "revolution",
            "disruption",
            "cleansing",
            "purification",
            "freedom"
        ],
    },
    "The Star": {
        "name": "The Star",
        "coreIntentions": "renewed hope, healing light, spiritual guidance, peaceful restoration, wish fulfillment",
        "meaning": "The Star pours healing waters from the cosmic well, reminding you that hope is not wishful thinking but a form of spiritual intelligence. After the storm, you become both the wounded and the healer.",
        "number": 17,
        "title": "Beacon of Cosmic Hope",
        "coreMeaning": "Hope — Healing, Renewal, and Divine Guidance",
        "keywords": [
            "sky",
            "hope",
            "faith",
            "renewal",
            "spirituality",
            "healing",
            "tranquility",
            "guidance",
            "wishes",
            "inspiration",
            "serenity",
            "calm",
            "optimism",
            "blessings",
            "divine guidance",
            "peace",
            "restoration",
            "rejuvenation",
            "promise",
            "future",
            "aspiration",
            "idealism",
            "generosity",
            "water bearer",
            "aquarius",
            "meditation",
            "flow",
            "grace"
        ],
    },
    "The Moon": {
        "name": "The Moon",
        "coreIntentions": "facing illusions, intuitive navigation, shadow integration, dream wisdom, psychic awakening",
        "meaning": "The Moon illuminates the winding path through illusion, where nothing is quite as it seems yet everything is exactly as it should be. Trust your inner compass when outer landmarks dissolve into shadow.",
        "number": 18,
        "title": "Guide Through Sacred Mystery",
        "coreMeaning": "Illusion — Intuition, Dreams, and Hidden Truths",
        "keywords": [
            "illusion",
            "fear",
            "anxiety",
            "subconscious",
            "intuition",
            "dreams",
            "deception",
            "confusion",
            "mystery",
            "imagination",
            "cycles",
            "madness",
            "hidden",
            "hidden truths",
            "uncertainty",
            "delusion",
            "fantasy",
            "nightmares",
            "secrets",
            "psychic",
            "emotions",
            "instinct",
            "unconscious",
            "shadow work",
            "reflection",
            "tides",
            "feminine"
        ],
    },
    "The Sun": {
        "name": "The Sun",
        "coreIntentions": "radiant joy, success achieved, pure happiness, childlike wonder, vital energy",
        "meaning": "The Sun radiates the joy of pure being, where every shadow is banished by the light of authentic self-expression. This is enlightenment with a child's heart—profound wisdom wrapped in simple delight.",
        "number": 19,
        "title": "Radiance of Pure Joy",
        "coreMeaning": "Joy — Vitality, Success, and Illuminated Truth",
        "keywords": [
            "joy",
            "success",
            "vitality",
            "positivity",
            "fun",
            "warmth",
            "happiness",
            "energy",
            "optimism",
            "freedom",
            "celebration",
            "enlightenment",
            "truth",
            "glory",
            "achievement",
            "illuminated truth",
            "life",
            "consciousness",
            "clarity",
            "confidence",
            "abundance",
            "growth",
            "childlike joy",
            "breakthrough",
            "victory",
            "radiance",
            "fulfillment",
            "light"
        ],
    },
    "Judgement": {
        "name": "Judgement",
        "coreIntentions": "spiritual calling, life review, soul awakening, purpose revealed, higher calling",
        "meaning": "Judgement sounds the cosmic call to awakening, where past, present, and future converge in a moment of profound reckoning. This is your spiritual alarm clock—time to rise and claim your highest calling.",
        "number": 20,
        "title": "The Great Awakening",
        "coreMeaning": "Calling — Rebirth, Reckoning, and Spiritual Awakening",
        "keywords": [
            "rebirth",
            "inner calling",
            "absolution",
            "judgment",
            "reflection",
            "reckoning",
            "awakening",
            "renewal",
            "forgiveness",
            "resurrection",
            "transformation",
            "decision",
            "spiritual awakening",
            "calling",
            "purpose",
            "evaluation",
            "assessment",
            "redemption",
            "second chance",
            "revelation",
            "karma",
            "accountability",
            "closure",
            "release",
            "ascension"
        ],
    },
    "The World": {
        "name": "The World",
        "coreIntentions": "cycle completion, total fulfillment, world mastery, cosmic consciousness, infinite possibility",
        "meaning": "The World celebrates the sacred completion where all elements dance in perfect harmony, yet hints at new spirals beginning. You have become whole by embracing every part of your journey as necessary and sacred.",
        "number": 21,
        "title": "The Cosmic Dancer",
        "coreMeaning": "Completion — Wholeness, Integration, and Cosmic Success",
        "keywords": [
            "interconnection",
            "completion",
            "accomplishment",
            "travel",
            "unity",
            "fulfillment",
            "wholeness",
            "success",
            "integration",
            "involvement",
            "cycles",
            "achievement",
            "cosmic consciousness",
            "cosmic success",
            "perfection",
            "celebration",
            "graduation",
            "mastery",
            "recognition",
            "satisfaction",
            "closure",
            "evolution",
            "enlightenment",
            "universe",
            "totality"
        ],
    },
    "Ace of Wands": {
        "name": "Ace of Wands",
        "coreIntentions": "creative spark, passionate beginning, new inspiration, spiritual fire, fresh energy",
        "meaning": "The Ace of Wands erupts with primal creative force, a lightning bolt of pure potential seeking expression through you. This is the divine spark that sets souls ablaze with purpose and passion.",
        "number": 22,
        "title": "The Primal Spark",
        "coreMeaning": "Inspiration — Creative Potential, New Energy, and Divine Spark",
        "keywords": [
            "fire",
            "inspiration",
            "new beginning",
            "creative spark",
            "potential",
            "passion",
            "enthusiasm",
            "initiative",
            "breakthrough",
            "opportunity",
            "courage",
            "growth",
            "birth",
            "innovation",
            "vitality",
            "fire energy",
            "divine spark",
            "motivation",
            "ambition",
            "raw power",
            "spontaneity",
            "spiritual gift",
            "awakening",
            "enterprise",
            "adventure"
        ]
    },
    "Two of Wands": {
        "name": "Two of Wands",
        "coreIntentions": "future planning, bold vision, personal power, strategic choice, confident direction",
        "meaning": "The Two of Wands stands at the threshold between dreaming and doing, holding the world in your hands while gazing at horizons yet unexplored. Power lies in the pause before the leap.",
        "number": 23,
        "title": "Visionary at the Threshold",
        "coreMeaning": "Planning — Personal Power, Future Vision, and Bold Decisions",
    },
    "Three of Wands": {
        "name": "Three of Wands",
        "coreIntentions": "expanding horizons, leadership emerging, vision manifesting, opportunities growing, progress ahead",
        "meaning": "The Three of Wands watches ships set sail carrying your dreams toward distant shores. Your initial efforts have taken flight; now comes the art of patient expectation and expanded vision.",
        "number": 24,
        "title": "Watcher of Distant Fires",
        "coreMeaning": "Expansion — Foresight, Progress, and Long-term Vision",
    },
    "Four of Wands": {
        "name": "Four of Wands",
        "coreIntentions": "joyful celebration, stable harmony, community blessing, achievement recognized, happy home",
        "meaning": "The Four of Wands raises the sacred pillars of celebration, marking territory where joy has taken root and community flourishes. This is success made sweeter by sharing its fruits.",
        "number": 25,
        "title": "Guardian of Sacred Celebration",
        "coreMeaning": "Celebration — Harmony, Homecoming, and Joyful Stability",
    },
    "Five of Wands": {
        "name": "Five of Wands",
        "coreIntentions": "creative conflict, healthy competition, dynamic tension, diverse perspectives, energetic challenge",
        "meaning": "The Five of Wands reveals creative friction where diverse energies clash and spark new possibilities. This chaos is not your enemy but the sacred fire that forges stronger solutions.",
        "number": 26,
        "title": "The Sacred Conflict",
        "coreMeaning": "Competition — Creative Tension, Conflict, and Dynamic Growth",
    },
    "Six of Wands": {
        "name": "Six of Wands",
        "coreIntentions": "public victory, success recognized, confidence rising, leadership acknowledged, triumph achieved",
        "meaning": "The Six of Wands rides high on earned victory, where inner fire has manifested as outer recognition. This triumph belongs to you—wear your laurels while remembering the journey continues.",
        "number": 27,
        "title": "Bearer of Golden Victory",
        "coreMeaning": "Victory — Recognition, Confidence, and Public Success",
    },
    "Seven of Wands": {
        "name": "Seven of Wands",
        "coreIntentions": "standing ground, defending position, courage tested, maintaining strength, protective stance",
        "meaning": "The Seven of Wands stands firm on the mountain you've climbed, defending your position against those who would claim your ground. Courage means standing for your truth when standing alone.",
        "number": 28,
        "title": "Defender of Sacred Ground",
        "coreMeaning": "Defense — Courage, Conviction, and Standing Your Ground",
    },
    "Eight of Wands": {
        "name": "Eight of Wands",
        "coreIntentions": "swift movement, rapid progress, quick communication, energy flowing, momentum building",
        "meaning": "The Eight of Wands accelerates like arrows loosed from the bow of divine timing, carrying your intentions swiftly toward their target. Movement happens now—trust the momentum you've created.",
        "number": 29,
        "title": "Arrows of Swift Destiny",
        "coreMeaning": "Speed — Swift Action, Movement, and Aligned Momentum",
    },
    "Nine of Wands": {
        "name": "Nine of Wands",
        "coreIntentions": "resilient persistence, final push, weathered strength, boundary setting, nearly there",
        "meaning": "The Nine of Wands embodies the warrior who still stands despite every battle scar, knowing one more test awaits. Your strength lies not in being unbroken but in continuing despite the breaks.",
        "number": 30,
        "title": "The Resilient Guardian",
        "coreMeaning": "Resilience — Persistence, Courage, and Final Tests",
    },
    "Ten of Wands": {
        "name": "Ten of Wands",
        "coreIntentions": "heavy burden, responsibility accepted, completion near, maximum effort, temporary overwhelm",
        "meaning": "The Ten of Wands carries the weight of success, where achievement brings responsibility that can either burden or teach you the art of delegation. True mastery knows when to share the load.",
        "number": 31,
        "title": "Bearer of Sacred Burdens",
        "coreMeaning": "Burden — Responsibility, Accomplishment, and the Weight of Success",
    },
    "Page of Wands": {
        "name": "Page of Wands",
        "coreIntentions": "enthusiastic exploration, creative messages, adventurous spirit, youthful energy, passionate discovery",
        "meaning": "The Page of Wands arrives as a dancing flame of possibility, bringing messages that ignite your creative spirit. This eager student of fire reminds you that enthusiasm is its own form of wisdom.",
        "number": 32,
        "title": "Messenger of Sacred Fire",
        "coreMeaning": "Discovery — Enthusiasm, New Ideas, and Creative Messages",
        "keywords": [
            "messenger",
            "enthusiasm",
            "exploration",
            "discovery",
            "free spirit",
            "adventure",
            "courage",
            "excitement",
            "new ideas",
            "creative spark",
            "inspiration",
            "good news",
            "passionate",
            "eager",
            "playful",
            "spontaneous",
            "optimistic",
            "fearless",
            "student of fire",
            "youthful energy",
            "fresh start",
            "creative message",
            "potential",
            "impulsive"
        ]
    },
    "Knight of Wands": {
        "name": "Knight of Wands",
        "coreIntentions": "passionate pursuit, adventurous action, impulsive courage, fiery charm, bold movement",
        "meaning": "The Knight of Wands charges forward on a steed of pure passion, transforming inspiration into action with fearless confidence. This warrior of fire knows that fortune favors the bold.",
        "number": 33,
        "title": "Warrior of Sacred Passion",
        "coreMeaning": "Adventure — Impulsiveness, Passion, and Bold Action",
        "keywords": [
            "adventure",
            "impulsive",
            "passionate",
            "energetic",
            "hot-tempered",
            "charming",
            "rebellious",
            "fearless",
            "confident",
            "daring",
            "action",
            "journey",
            "haste",
            "warrior of fire",
            "courageous",
            "risk-taker",
            "charismatic",
            "bold",
            "restless",
            "competitive",
            "traveler",
            "spontaneous action",
            "quest for passion",
            "fiery pursuit"
        ]
    },
    "Queen of Wands": {
        "name": "Queen of Wands",
        "coreIntentions": "confident leadership, warm authority, creative mastery, magnetic presence, generous spirit",
        "meaning": "The Queen of Wands radiates magnetic confidence, ruling her realm with warmth that nurtures and fire that inspires. She shows you how to be both torch and hearth—illuminating and warming in equal measure.",
        "number": 34,
        "title": "Sovereign of Sacred Flame",
        "coreMeaning": "Confidence — Charisma, Independence, and Warm Authority",
        "keywords": [
            "confident",
            "independent",
            "charismatic",
            "bold",
            "creative",
            "passionate",
            "warm",
            "vibrant",
            "courageous",
            "determined",
            "outgoing",
            "magnetic",
            "queen of fire",
            "optimistic",
            "friendly",
            "energetic",
            "inspiring",
            "generous",
            "wholehearted",
            "vivacious",
            "self-assured",
            "fertility",
            "leadership",
            "radiant"
        ]
    },
    "King of Wands": {
        "name": "King of Wands",
        "coreIntentions": "visionary leadership, inspired authority, natural charisma, entrepreneurial spirit, motivating others",
        "meaning": "The King of Wands transforms vision into empire through the marriage of inspiration and discipline. This master of fire demonstrates how to lead with passion while maintaining the wisdom to direct its flow.",
        "number": 35,
        "title": "Master of Sacred Vision",
        "coreMeaning": "Leadership — Vision, Charisma, and Inspired Authority",
        "keywords": [
            "natural leader",
            "visionary",
            "entrepreneur",
            "charismatic",
            "bold",
            "inspiring",
            "confident",
            "king of fire",
            "generous",
            "motivating",
            "influential",
            "commanding",
            "optimistic",
            "adventurous",
            "passionate leader",
            "courageous",
            "pioneering",
            "ambitious",
            "creative vision",
            "masterful",
            "noble",
            "expansive",
            "authoritative",
            "protective"
        ]
    },
    "Ace of Cups": {
        "name": "Ace of Cups",
        "coreIntentions": "emotional beginning, love flowing, heart opening, intuitive gifts, spiritual awakening",
        "meaning": "The Ace of Cups overflows with the nectar of divine love, offering you a chalice filled with infinite emotional and spiritual possibility. Drink deeply—this is the water that transforms deserts into gardens.",
        "number": 36,
        "title": "The Divine Chalice",
        "coreMeaning": "Love — New Emotions, Spiritual Connection, and Open Heart",
        "keywords": [
            "water",
            "new love",
            "emotional beginning",
            "intuition",
            "spiritual awakening",
            "creativity",
            "compassion",
            "emotional release",
            "joy",
            "inner peace",
            "fertility",
            "new relationship",
            "forgiveness",
            "divine love",
            "emotional renewal",
            "happiness",
            "fulfillment",
            "abundance",
            "healing",
            "receptivity",
            "grace",
            "blessing",
            "emotional gift",
            "psychic opening",
            "heart opening"
        ]
    },
    "Two of Cups": {
        "name": "Two of Cups",
        "coreIntentions": "soul recognition, mutual attraction, emotional balance, partnership forming, love connection",
        "meaning": "The Two of Cups creates sacred space where two souls recognize themselves in each other's eyes. This divine mirror reflects not just romance but the profound meeting of any two hearts in truth.",
        "number": 37,
        "title": "The Sacred Meeting",
        "coreMeaning": "Partnership — Connection, Mutual Love, and Sacred Union",
        "keywords": [
            "partnership",
            "union",
            "love",
            "attraction",
            "connection",
            "relationships",
            "harmony",
            "balance",
            "mutual respect",
            "soulmate",
            "romance",
            "friendship",
            "equality",
            "proposal",
            "engagement",
            "truce",
            "cooperation",
            "healing",
            "reconciliation",
            "chemistry",
            "mutual attraction",
            "unified",
            "bond",
            "sacred union"
        ]
    },
    "Three of Cups": {
        "name": "Three of Cups",
        "coreIntentions": "friendship celebration, joyful gathering, community support, shared happiness, social harmony",
        "meaning": "The Three of Cups raises a toast to the divine trinity of friendship, where individual streams merge into a river of shared joy. Community becomes the chalice that holds more than any single cup.",
        "number": 38,
        "title": "Celebration of Sacred Bonds",
        "coreMeaning": "Friendship — Celebration, Community, and Shared Joy",
    },
    "Four of Cups": {
        "name": "Four of Cups",
        "coreIntentions": "emotional withdrawal, contemplation needed, reevaluating options, temporary apathy, inner processing",
        "meaning": "The Four of Cups sits in contemplative withdrawal, where the soul reassesses its emotional landscape before accepting new offerings. Sometimes the greatest gift is the pause before receiving.",
        "number": 39,
        "title": "The Sacred Contemplation",
        "coreMeaning": "Apathy — Contemplation, Reevaluation, and Emotional Withdrawal",
    },
    "Five of Cups": {
        "name": "Five of Cups",
        "coreIntentions": "processing grief, accepting loss, emotional release, finding hope, partial healing",
        "meaning": "The Five of Cups honors the sacred grief that waters future joy, teaching that loss and gain dance together in the human heart. What remains standing often holds more than what has fallen.",
        "number": 40,
        "title": "Teacher of Sacred Grief",
        "coreMeaning": "Loss — Grief, Regret, and Finding What Remains",
    },
    "Six of Cups": {
        "name": "Six of Cups",
        "coreIntentions": "childhood healing, innocent joy, nostalgic comfort, karmic return, sweet memories",
        "meaning": "The Six of Cups opens the treasure chest of memory where innocence is preserved in amber, offering its sweetness to heal present wounds. The inner child holds medicine the adult has forgotten.",
        "number": 41,
        "title": "Keeper of Sweet Memory",
        "coreMeaning": "Nostalgia — Innocence, Memories, and Childlike Joy",
    },
    "Seven of Cups": {
        "name": "Seven of Cups",
        "coreIntentions": "emotional choices, imagination active, wishful thinking, multiple options, clarity needed",
        "meaning": "The Seven of Cups presents a mystical array of possibilities, each chalice holding a different dream or illusion. Wisdom lies in discerning which cups hold nectar and which hold only mist.",
        "number": 42,
        "title": "Weaver of Sacred Dreams",
        "coreMeaning": "Illusion — Choices, Fantasy, and Wishful Thinking",
    },
    "Eight of Cups": {
        "name": "Eight of Cups",
        "coreIntentions": "moving forward, leaving behind, spiritual quest, emotional evolution, necessary departure",
        "meaning": "The Eight of Cups turns away from what no longer nourishes, embarking on a pilgrimage toward deeper truth. This departure is not defeat but the courage to seek the ocean when pools no longer satisfy.",
        "number": 43,
        "title": "Pilgrim of Deeper Waters",
        "coreMeaning": "Departure — Walking Away, Seeking More, and Spiritual Quest",
    },
    "Nine of Cups": {
        "name": "Nine of Cups",
        "coreIntentions": "emotional satisfaction, contentment found, wishes granted, personal happiness, grateful heart",
        "meaning": "The Nine of Cups sits in the glow of wishes fulfilled, reminding you that contentment is both destination and journey. This is the smile of one who has learned the alchemy of gratitude.",
        "number": 44,
        "title": "Master of Heart's Desire",
        "coreMeaning": "Satisfaction — Emotional Fulfillment, Wishes Granted, and Contentment",
        "keywords": ["gratitude"],
    },
    "Ten of Cups": {
        "name": "Ten of Cups",
        "coreIntentions": "family harmony, emotional fulfillment, lasting happiness, perfect contentment, rainbow blessings",
        "meaning": "The Ten of Cups paints the rainbow bridge connecting hearts in perfect harmony, where love has created its own kingdom. This is happiness that ripples outward, blessing all it touches.",
        "number": 45,
        "title": "The Rainbow's Promise",
        "coreMeaning": "Harmony — Family Bliss, Emotional Fulfillment, and Lasting Joy",
        "keywords": [
            "happiness",
            "fulfillment",
            "emotional contentment",
            "family harmony",
            "divine love",
            "blissful relationships",
            "peace",
            "emotional abundance",
            "happy family",
            "rainbow",
            "wishes fulfilled",
            "joyful",
            "domestic bliss",
            "true happiness",
            "loving community",
            "emotional security",
            "happily ever after",
            "alignment",
            "gratitude",
            "celebration",
            "wholeness",
            "completion",
            "emotional success",
            "joy"
        ]
    },
    "Page of Cups": {
        "name": "Page of Cups",
        "coreIntentions": "intuitive messages, emotional learning, creative beginning, sensitive awareness, gentle start",
        "meaning": "The Page of Cups arrives bearing messages from the realm of feeling, where intuition speaks in symbols and synchronicities. This gentle messenger teaches that sensitivity is a superpower.",
        "number": 46,
        "title": "Messenger of Sacred Feeling",
        "coreMeaning": "Intuition — Emotional Messages, Creativity, and Gentle Beginnings",
        "keywords": [
            "emotional message",
            "intuition",
            "creativity",
            "sensitivity",
            "dreamer",
            "romantic",
            "gentle",
            "artistic",
            "psychic ability",
            "emotional beginning",
            "inner child",
            "imagination",
            "idealistic",
            "tender",
            "innocent",
            "loving message",
            "surprise",
            "synchronicity",
            "student of water",
            "emotional learning",
            "sweet",
            "vulnerable",
            "receptive",
            "poetic"
        ]
    },
    "Knight of Cups": {
        "name": "Knight of Cups",
        "coreIntentions": "romantic pursuit, emotional quest, following heart, creative vision, idealistic journey",
        "meaning": "The Knight of Cups rides on waves of romantic idealism, bearing the grail of emotional truth with chivalrous devotion. This quester seeks not just love but the sacred in every connection.",
        "number": 47,
        "title": "Quester of Sacred Hearts",
        "coreMeaning": "Romance — Emotional Quest, Idealism, and Following the Heart",
        "keywords": [
            "romantic",
            "charming",
            "imaginative",
            "sensitive",
            "artistic",
            "dreamer",
            "idealistic",
            "emotional quest",
            "knight in shining armor",
            "proposal",
            "invitation",
            "following heart",
            "creative",
            "intuitive",
            "graceful",
            "diplomatic",
            "seductive",
            "warrior of water",
            "emotional offer",
            "chivalrous",
            "poetic soul",
            "quest for love",
            "emotional pursuit",
            "visionary"
        ]
    },
    "Queen of Cups": {
        "name": "Queen of Cups",
        "coreIntentions": "emotional mastery, intuitive wisdom, compassionate leadership, nurturing presence, deep feeling",
        "meaning": "The Queen of Cups reigns over the ocean of emotion with compassionate wisdom, holding space for all feelings without drowning in any. She shows how to be deeply empathic while maintaining your sacred center.",
        "number": 48,
        "title": "Oracle of Sacred Waters",
        "coreMeaning": "Compassion — Emotional Mastery, Intuitive Wisdom, and Nurturing",
        "keywords": [
            "compassion",
            "compassionate",
            "intuitive",
            "nurturing",
            "emotional",
            "empathic",
            "psychic",
            "caring",
            "supportive",
            "healing",
            "queen of water",
            "sensitive",
            "loving",
            "creative",
            "dreamy",
            "romantic",
            "maternal",
            "spiritual",
            "receptive",
            "emotional intelligence",
            "wise woman",
            "heart-centered",
            "devoted",
            "gentle strength",
            "deep feeling"
        ]
    },
    "King of Cups": {
        "name": "King of Cups",
        "coreIntentions": "emotional maturity, balanced feelings, wise counsel, calm mastery, diplomatic strength",
        "meaning": "The King of Cups masters the art of emotional leadership, navigating stormy seas with calm authority. This sovereign shows how to rule the heart's realm with both depth and stability.",
        "number": 49,
        "title": "Navigator of Sacred Depths",
        "coreMeaning": "Emotional Control — Maturity, Balanced Feelings, and Wise Leadership",
        "keywords": [
            "emotional balance",
            "compassionate",
            "diplomatic",
            "calm",
            "caring",
            "tolerant",
            "king of water",
            "wise counselor",
            "emotionally stable",
            "generous",
            "reliable",
            "devoted",
            "family-oriented",
            "understanding",
            "artistic mastery",
            "emotional control",
            "mature emotions",
            "patient",
            "advisor",
            "spiritual wisdom",
            "healing presence",
            "benevolent",
            "supportive leader",
            "intuitive wisdom"
        ]
    },
    "Ace of Swords": {
        "name": "Ace of Swords",
        "coreIntentions": "mental clarity, breakthrough thinking, truth cutting, new understanding, clear communication",
        "meaning": "The Ace of Swords cuts through confusion with the blade of absolute clarity, offering you the power to separate truth from illusion with a single stroke. This is the mind's enlightenment moment.",
        "number": 50,
        "title": "Blade of Pure Truth",
        "coreMeaning": "Clarity — Mental Breakthrough, Truth, and New Understanding",
        "keywords": [
            "mental clarity",
            "breakthrough",
            "new idea",
            "truth",
            "justice",
            "mental force",
            "clear thinking",
            "communication",
            "new perspective",
            "realization",
            "power",
            "victory",
            "sharp mind",
            "decision",
            "cutting through",
            "insight",
            "intellect",
            "focus",
            "determination",
            "logic",
            "analysis",
            "revelation",
            "mental gift",
            "discernment"
        ]
    },
    "Two of Swords": {
        "name": "Two of Swords",
        "coreIntentions": "difficult choice, mental balance, blocked vision, indecision resolved, seeing clearly",
        "meaning": "The Two of Swords balances on the knife's edge of decision, where the blindfold of impartiality allows inner wisdom to weigh options without prejudice. Peace exists in the pause before choice.",
        "number": 51,
        "title": "Guardian of Sacred Balance",
        "coreMeaning": "Indecision — Difficult Choices, Mental Balance, and Stalemate",
    },
    "Three of Swords": {
        "name": "Three of Swords",
        "coreIntentions": "heartbreak healing, necessary pain, emotional truth, sorrow releasing, wound cleansing",
        "meaning": "The Three of Swords pierces the heart with truth that heals through hurting, revealing that some pain is the price of clarity. This sacred wound creates space for more authentic love.",
        "number": 52,
        "title": "The Sacred Piercing",
        "coreMeaning": "Heartbreak — Pain, Sorrow, and Healing Through Truth",
        "keywords": [
            "heartbreak",
            "sorrow",
            "grief",
            "loss",
            "betrayal",
            "painful truth",
            "separation",
            "sadness",
            "tears",
            "loneliness",
            "depression",
            "emotional pain",
            "trauma",
            "hurt",
            "rejection",
            "suffering",
            "emotional release",
            "healing crisis",
            "harsh words",
            "conflict",
            "disappointment",
            "painful realization",
            "emotional wound",
            "heartache"
        ]
    },
    "Four of Swords": {
        "name": "Four of Swords",
        "coreIntentions": "mental rest, peaceful recovery, contemplation time, healing pause, quiet restoration",
        "meaning": "The Four of Swords creates sanctuary for the battle-weary mind, where rest becomes an act of wisdom rather than surrender. In stillness, the sword of consciousness resharpens itself.",
        "number": 53,
        "title": "Sanctuary of Sacred Rest",
        "coreMeaning": "Rest — Mental Peace, Recovery, and Contemplation",
    },
    "Five of Swords": {
        "name": "Five of Swords",
        "coreIntentions": "conflict resolution, unfair situation, empty victory, choosing integrity, learning humility",
        "meaning": "The Five of Swords questions the price of victory when winning costs more than losing would have. This teacher arrives when you must choose between being right and being wise.",
        "number": 54,
        "title": "Teacher of Hollow Victory",
        "coreMeaning": "Conflict — Winning at Cost, Discord, and Pyrrhic Victory",
    },
    "Six of Swords": {
        "name": "Six of Swords",
        "coreIntentions": "mental transition, moving forward, leaving troubles, calmer waters, gradual improvement",
        "meaning": "The Six of Swords navigates the crossing from turbulent to calmer waters, carrying only the wisdom earned from storms. This journey requires leaving some baggage on the shore behind you.",
        "number": 55,
        "title": "Ferryman to Calmer Shores",
        "coreMeaning": "Transition — Moving Forward, Leaving Troubles, and Mental Journey",
    },
    "Seven of Swords": {
        "name": "Seven of Swords",
        "coreIntentions": "strategic thinking, independent action, clever solutions, calculated risk, mental agility",
        "meaning": "The Seven of Swords masters the art of strategic thinking, knowing when to move in shadows and when to stand in light. This is not deception but the wisdom of choosing your revelations.",
        "number": 56,
        "title": "Master of Sacred Strategy",
        "coreMeaning": "Strategy — Cunning, Stealth, and Getting Away With It",
        "keywords": [
            "deception",
            "strategy",
            "sneakiness",
            "betrayal",
            "trickery",
            "lies",
            "manipulation",
            "cunning",
            "scheming",
            "dishonesty",
            "theft",
            "stealth",
            "acting alone",
            "hidden agenda",
            "escape",
            "avoidance",
            "getting away with something",
            "secret plan",
            "mental challenge",
            "outsmarting",
            "tactical",
            "evasion",
            "lone wolf",
            "diplomacy"
        ]
    },
    "Eight of Swords": {
        "name": "Eight of Swords",
        "coreIntentions": "mental freedom, limiting beliefs, perceived trap, victim mentality, breaking free",
        "meaning": "The Eight of Swords reveals prisons built from thoughts, where the binding ropes are beliefs you've forgotten you can untie. Freedom begins the moment you realize the cage has no lock.",
        "number": 57,
        "title": "Liberator of Mental Chains",
        "coreMeaning": "Restriction — Self-Imposed Limits, Mental Prison, and Victim Mentality",
    },
    "Nine of Swords": {
        "name": "Nine of Swords",
        "coreIntentions": "releasing anxiety, nightmare ending, mental anguish, worry dissolving, dawn approaching",
        "meaning": "The Nine of Swords sits vigil with the anxious mind in its darkest hour, where fears multiply in the echo chamber of night. Dawn always comes for those who remember they survived every previous darkness.",
        "number": 58,
        "title": "Guardian Through Dark Night",
        "coreMeaning": "Anxiety — Mental Anguish, Worry, and Nightmares",
    },
    "Ten of Swords": {
        "name": "Ten of Swords",
        "coreIntentions": "rock bottom, painful ending, complete release, nowhere but up, transformation ready",
        "meaning": "The Ten of Swords marks the death of a mental paradigm, where total defeat becomes the ground for total transformation. Rock bottom is solid foundation for rebuilding with wisdom.",
        "number": 59,
        "title": "Dawn After Darkest Night",
        "coreMeaning": "Defeat — Rock Bottom, Ending, and Painful Completion",
        "keywords": [
            "painful ending",
            "betrayal",
            "backstabbing",
            "defeat",
            "crisis",
            "bottoming out",
            "exhaustion",
            "dead end",
            "victim mentality",
            "rock bottom",
            "martyrdom",
            "dramatic ending",
            "overkill",
            "ruin",
            "failure",
            "collapse",
            "finality",
            "inevitable end",
            "hitting bottom",
            "nowhere to go but up",
            "darkest before dawn",
            "complete defeat",
            "transformation point",
            "rebirth pending"
        ]
    },
    "Page of Swords": {
        "name": "Page of Swords",
        "coreIntentions": "curious mind, truth seeking, mental agility, clear communication, vigilant awareness",
        "meaning": "The Page of Swords wields curiosity like a blade, cutting through assumptions with questions that reveal hidden truths. This messenger brings news that challenges you to think in new ways.",
        "number": 60,
        "title": "Seeker of Sharp Truths",
        "coreMeaning": "Curiosity — Mental Energy, New Ideas, and Vigilant Observation",
        "keywords": [
            "vigilant",
            "curious",
            "mental energy",
            "new ideas",
            "communication",
            "truth seeker",
            "alert",
            "observant",
            "intellectual",
            "news",
            "gossip",
            "spy",
            "investigative",
            "questioning",
            "analytical",
            "student of air",
            "mental agility",
            "sharp wit",
            "defensive",
            "cautious",
            "messenger of truth",
            "youthful intellect",
            "restless mind",
            "inquisitive"
        ]
    },
    "Knight of Swords": {
        "name": "Knight of Swords",
        "coreIntentions": "swift action, direct communication, ambitious drive, quick thinking, determined pursuit",
        "meaning": "The Knight of Swords charges into battle for truth with the speed of thought itself, cutting through deception with fierce intelligence. This warrior of the mind knows that sometimes swift action prevents greater harm.",
        "number": 61,
        "title": "Champion of Swift Justice",
        "coreMeaning": "Ambition — Quick Action, Mental Force, and Determined Pursuit",
        "keywords": [
            "ambitious",
            "action-oriented",
            "driven",
            "fast-thinking",
            "assertive",
            "direct",
            "impatient",
            "intellectual",
            "courageous",
            "warrior of air",
            "swift action",
            "determined",
            "aggressive",
            "rushing forward",
            "single-minded",
            "authoritative",
            "mental force",
            "champion of truth",
            "quick decision",
            "charging ahead",
            "quest for truth",
            "mental pursuit",
            "brave",
            "fierce"
        ]
    },
    "Queen of Swords": {

        "name": "Queen of Swords",
        "coreIntentions": "clear boundaries, direct wisdom, independent thinking, experienced judgment, mental mastery",
        "meaning": "The Queen of Swords sees through veils with perceptive clarity, wielding truth with the precision of a surgeon and the grace of a diplomat. Her boundaries are not walls but sacred definitions.",
        "number": 62,
        "title": "Keeper of Crystal Clarity",
        "coreMeaning": "Perception — Clear Boundaries, Sharp Intellect, and Direct Communication",
        "keywords": [
            "perceptive",
            "independent",
            "clear boundaries",
            "direct communication",
            "intelligent",
            "unbiased",
            "truthful",
            "experienced",
            "queen of air",
            "sharp wit",
            "discerning",
            "objective",
            "sophisticated",
            "professional",
            "honest",
            "principled",
            "organized",
            "logical",
            "fair-minded",
            "mature wisdom",
            "mental clarity",
            "constructive criticism",
            "strategic",
            "dignified"
        ]
    },
    "King of Swords": {

        "name": "King of Swords",
        "coreIntentions": "intellectual authority, objective truth, fair leadership, strategic thinking, wise command",
        "meaning": "The King of Swords rules the realm of mind with ethical authority, where justice and wisdom unite in service of truth. This sovereign shows how to wield intellectual power with moral clarity.",
        "number": 63,
        "title": "Sovereign of Sacred Justice",
        "coreMeaning": "Authority — Mental Mastery, Fair Judgment, and Intellectual Power",
        "keywords": [
            "intellectual power",
            "authority",
            "truth",
            "justice",
            "analytical",
            "king of air",
            "ethical",
            "moral authority",
            "clear thinking",
            "rational",
            "assertive",
            "professional",
            "strategic",
            "impartial",
            "stern",
            "commanding",
            "mental discipline",
            "wise judgment",
            "law and order",
            "structured thinking",
            "expert",
            "decisive leader",
            "intellectual mastery",
            "fair"
        ]
    },
    "Ace of Pentacles": {

        "name": "Ace of Pentacles",
        "coreIntentions": "material opportunity, prosperity beginning, tangible manifestation, earthly blessings, golden seeds",
        "meaning": "The Ace of Pentacles offers a golden seed pregnant with material and spiritual abundance. Plant it with intention, for this gift from earth's treasury will grow into whatever you nurture it to become.",
        "number": 64,
        "title": "The Golden Seed",
        "coreMeaning": "Opportunity — Material Beginnings, Prosperity, and Manifestation",
        "keywords": [
            "earth",
            "new opportunity",
            "manifestation",
            "prosperity",
            "new job",
            "material gain",
            "abundance",
            "security",
            "potential wealth",
            "grounding",
            "new venture",
            "investment",
            "practical beginning",
            "tangible results",
            "material gift",
            "foundation",
            "health",
            "trust",
            "resources",
            "stability",
            "physical gift",
            "earthly blessing",
            "seed",
            "golden opportunity",
            "success"
        ]
    },
    "Two of Pentacles": {

        "name": "Two of Pentacles",
        "coreIntentions": "juggling priorities, finding balance, flexible approach, resource management, dynamic flow",
        "meaning": "The Two of Pentacles dances with change, juggling resources with the grace of one who knows that balance is not stillness but constant, conscious adjustment. Master the rhythm of give and take.",
        "number": 65,
        "title": "Dancer of Sacred Balance",
        "coreMeaning": "Balance — Juggling Priorities, Adaptability, and Resource Management",
    },
    "Three of Pentacles": {

        "name": "Three of Pentacles",
        "coreIntentions": "team collaboration, skill recognition, quality work, apprentice learning, creative partnership",
        "meaning": "The Three of Pentacles builds cathedrals through collaboration, where individual mastery serves the collective vision. This is the sacred mathematics where one plus one plus one equals infinity.",
        "number": 66,
        "title": "Master of Sacred Craft",
        "coreMeaning": "Collaboration — Teamwork, Skill Building, and Quality Work",
    },
    "Four of Pentacles": {

        "name": "Four of Pentacles",
        "coreIntentions": "financial security, material control, resource protection, stable foundation, conscious possession",
        "meaning": "The Four of Pentacles grips tightly to accumulated treasure, teaching the delicate balance between saving and hoarding. Security becomes prison when fear of loss overshadows joy of having.",
        "number": 67,
        "title": "Guardian of the Treasure",
        "coreMeaning": "Control — Holding On, Security, and Fear of Loss",
    },
    "Five of Pentacles": {
        "name": "Five of Pentacles",
        "coreIntentions": "overcoming hardship, seeking help, spiritual richness, material challenge, finding support",
        "meaning": "The Five of Pentacles illuminates the sanctuary glowing just beyond the storm, reminding you that help exists for those willing to see it. In your darkest winter, warmth is closer than you think.",
        "number": 68,
        "title": "Light Beyond the Storm",
        "coreMeaning": "Hardship — Material Loss, Isolation, and Spiritual Poverty",
    },
    "Six of Pentacles": {
        "name": "Six of Pentacles",
        "coreIntentions": "generous sharing, fair exchange, balanced giving, charity flowing, reciprocal blessing",
        "meaning": "The Six of Pentacles balances the scales of giving and receiving, understanding that generosity creates the current in which abundance flows. This is karma made visible through conscious exchange.",
        "number": 69,
        "title": "Keeper of Sacred Exchange",
        "coreMeaning": "Generosity — Sharing Wealth, Charity, and Fair Exchange",
    },
    "Seven of Pentacles": {
        "name": "Seven of Pentacles",
        "coreIntentions": "patient investment, long-term vision, evaluating progress, sustainable growth, harvest coming",
        "meaning": "The Seven of Pentacles pauses in the garden to assess growth, knowing that some harvests require patience beyond a single season. This is the wisdom of tending what takes time to ripen.",
        "number": 70,
        "title": "Gardener of Patient Wealth",
        "coreMeaning": "Assessment — Long-term Investment, Patience, and Evaluating Progress",
    },
    "Eight of Pentacles": {
        "name": "Eight of Pentacles",
        "coreIntentions": "dedicated practice, skill mastery, quality focus, apprentice discipline, craftsman dedication",
        "meaning": "The Eight of Pentacles transforms work into meditation, where repetition becomes refinement and practice becomes prayer. This is mastery earned one careful stroke at a time.",
        "number": 71,
        "title": "The Sacred Apprentice",
        "coreMeaning": "Craftsmanship — Dedication, Skill Development, and Quality Focus",
    },
    "Nine of Pentacles": {
        "name": "Nine of Pentacles",
        "coreIntentions": "earned luxury, self sufficiency, refined success, independent wealth, graceful abundance",
        "meaning": "The Nine of Pentacles dwells in the garden of self-sufficiency, where disciplined effort has bloomed into graceful abundance. This is wealth that includes but transcends material possessions.",
        "number": 72,
        "title": "Sovereign of Self-Made Grace",
        "coreMeaning": "Independence — Self-Sufficiency, Luxury, and Earned Abundance",
    },
    "Ten of Pentacles": {
        "name": "Ten of Pentacles",
        "coreIntentions": "lasting legacy, generational wealth, family success, material mastery, permanent achievement",
        "meaning": "The Ten of Pentacles builds legacy that transcends generations, where wealth becomes wisdom passed through bloodlines and chosen families. This is abundance that outlives its creators.",
        "number": 73,
        "title": "Architect of Living Legacy",
        "coreMeaning": "Legacy — Generational Wealth, Family Success, and Lasting Stability",
        "keywords": [
            "wealth",
            "inheritance",
            "family legacy",
            "old money",
            "tradition",
            "financial security",
            "accomplishment",
            "stability",
            "established",
            "ancestry",
            "long-term success",
            "contribution",
            "affluence",
            "permanent",
            "solid foundations",
            "conventionality",
            "dynasty",
            "material abundance",
            "family business",
            "retirement",
            "generations",
            "culmination",
            "lasting success",
            "prosperity"
        ]
    },
    "Page of Pentacles": {
        "name": "Page of Pentacles",
        "coreIntentions": "practical learning, steady progress, grounded approach, new skills, material beginnings",
        "meaning": "The Page of Pentacles studies the book of earth with devoted attention, finding magic in the practical and sacred in the mundane. This student knows that mastery begins with beginner's mind.",
        "number": 74,
        "title": "Student of Earthly Magic",
        "coreMeaning": "Study — New Skills, Practical Learning, and Material Opportunity",
        "keywords": [
            "student",
            "ambition",
            "new skill",
            "practical",
            "diligent",
            "studious",
            "apprentice",
            "manifestation",
            "planning",
            "opportunity",
            "loyal",
            "patient",
            "methodical",
            "grounded",
            "reliable",
            "student of earth",
            "material message",
            "scholarship",
            "dedication",
            "focus",
            "practical news",
            "beginner",
            "steady progress",
            "tangible goals"
        ]
    },
    "Knight of Pentacles": {
        "name": "Knight of Pentacles",
        "coreIntentions": "methodical progress, reliable effort, patient work, steady advancement, persistent dedication",
        "meaning": "The Knight of Pentacles advances with the patience of mountains and the persistence of rivers carving canyons. This steady warrior proves that slow and steady not only finishes but masters the race.",
        "number": 75,
        "title": "Guardian of Steady Progress",
        "coreMeaning": "Persistence — Methodical Progress, Reliability, and Determined Work",
        "keywords": [
            "methodical",
            "reliable",
            "patient",
            "conservative",
            "dedicated",
            "persistent",
            "responsible",
            "hardworking",
            "practical",
            "routine",
            "steady progress",
            "warrior of earth",
            "dutiful",
            "thorough",
            "cautious",
            "trustworthy",
            "determined",
            "slow and steady",
            "enduring",
            "materialistic",
            "quest for stability",
            "physical pursuit",
            "unwavering",
            "disciplined"
        ]
    },
    "Queen of Pentacles": {
        "name": "Queen of Pentacles",
        "coreIntentions": "practical nurturing, abundant provision, earthly wisdom, material comfort, grounded care",
        "meaning": "The Queen of Pentacles creates abundance through nurturing, transforming resources into comfort and security for all in her realm. She shows that practical magic is the most powerful spell.",
        "number": 76,
        "title": "Mother of Abundant Earth",
        "coreMeaning": "Nurturing — Practical Care, Material Comfort, and Grounded Wisdom",
        "keywords": [
            "nurturing",
            "practical",
            "providing",
            "motherly",
            "down-to-earth",
            "resourceful",
            "queen of earth",
            "generous",
            "reliable",
            "warm-hearted",
            "sensible",
            "luxurious",
            "homely",
            "abundant",
            "security-focused",
            "business-minded",
            "fertile",
            "welcoming",
            "material comfort",
            "financial security",
            "nature-loving",
            "grounded wisdom",
            "prosperity",
            "supportive"
        ]
    },
    "King of Pentacles": {
        "name": "King of Pentacles",
        "coreIntentions": "material mastery, wealth consciousness, successful leadership, established prosperity, generous authority",
        "meaning": "The King of Pentacles transforms vision into empire through patient cultivation and wise investment. This master of manifestation shows that true wealth serves rather than enslaves.",
        "number": 77,
        "title": "Master of Manifested Wealth",
        "coreMeaning": "Success — Material Mastery, Business Acumen, and Generous Leadership",
        "keywords": [
            "wealth",
            "business success",
            "leadership",
            "security",
            "discipline",
            "abundance",
            "king of earth",
            "reliable",
            "generous provider",
            "practical wisdom",
            "enterprising",
            "steady",
            "masterful",
            "materialistic",
            "protective",
            "conservative",
            "established",
            "financial security",
            "empire builder",
            "patient investor",
            "grounded authority",
            "prosperous",
            "accomplished",
            "stable leadership"
        ]
    }
};
