export const symbols = {
    "0": {"symbol": "Abyss", "category": "creation and cosmos"},
    "1": {"symbol": "Air", "category": "creation and cosmos"},
    "2": {"symbol": "Ashes", "category": "creation and cosmos"},
    "3": {"symbol": "Black", "category": "creation and cosmos"},
    "4": {"symbol": "Blue", "category": "creation and cosmos"},
    "5": {"symbol": "Brown", "category": "creation and cosmos"},
    "6": {"symbol": "Bubble", "category": "creation and cosmos"},
    "7": {"symbol": "Cloud", "category": "creation and cosmos"},
    "8": {"symbol": "Color", "category": "creation and cosmos"},
    "9": {"symbol": "Comet", "category": "creation and cosmos"},
    "10": {"symbol": "Crack", "category": "creation and cosmos"},
    "11": {"symbol": "Crescent", "category": "creation and cosmos"},
    "12": {"symbol": "Crystal", "category": "creation and cosmos"},
    "13": {"symbol": "Darkness", "category": "creation and cosmos"},
    "14": {"symbol": "Dawn", "category": "creation and cosmos"},
    "15": {"symbol": "Desert", "category": "creation and cosmos"},
    "16": {"symbol": "Dew", "category": "creation and cosmos"},
    "17": {"symbol": "Dot/Bindu", "category": "creation and cosmos"},
    "18": {"symbol": "Dusk", "category": "creation and cosmos"},
    "19": {"symbol": "Eclipse", "category": "creation and cosmos"},
    "20": {"symbol": "Egg", "category": "creation and cosmos"},
    "21": {"symbol": "Fire", "category": "creation and cosmos"},
    "22": {"symbol": "Flood", "category": "creation and cosmos"},
    "23": {"symbol": "Fog", "category": "creation and cosmos"},
    "24": {"symbol": "Gold", "category": "creation and cosmos"},
    "25": {"symbol": "Gray", "category": "creation and cosmos"},
    "26": {"symbol": "Green", "category": "creation and cosmos"},
    "27": {"symbol": "Island", "category": "creation and cosmos"},
    "28": {"symbol": "Lake/Pond", "category": "creation and cosmos"},
    "29": {"symbol": "Lightning", "category": "creation and cosmos"},
    "30": {"symbol": "Marsh", "category": "creation and cosmos"},
    "31": {"symbol": "Moon", "category": "creation and cosmos"},
    "32": {"symbol": "Mountain", "category": "creation and cosmos"},
    "33": {"symbol": "Night", "category": "creation and cosmos"},
    "34": {"symbol": "Ocean", "category": "creation and cosmos"},
    "35": {"symbol": "One", "category": "creation and cosmos"},
    "36": {"symbol": "Orange", "category": "creation and cosmos"},
    "37": {"symbol": "Purple", "category": "creation and cosmos"},
    "38": {"symbol": "Rain", "category": "creation and cosmos"},
    "39": {"symbol": "Rainbow", "category": "creation and cosmos"},
    "40": {"symbol": "Red", "category": "creation and cosmos"},
    "41": {"symbol": "River", "category": "creation and cosmos"},
    "42": {"symbol": "Salt", "category": "creation and cosmos"},
    "43": {"symbol": "Sky", "category": "creation and cosmos"},
    "44": {"symbol": "Snow", "category": "creation and cosmos"},
    "45": {"symbol": "Solstice", "category": "creation and cosmos"},
    "46": {"symbol": "Spark", "category": "creation and cosmos"},
    "47": {"symbol": "Spiral", "category": "creation and cosmos"},
    "48": {"symbol": "Star", "category": "creation and cosmos"},
    "49": {"symbol": "Stone", "category": "creation and cosmos"},
    "50": {"symbol": "Storm", "category": "creation and cosmos"},
    "51": {"symbol": "Sun", "category": "creation and cosmos"},
    "52": {"symbol": "Sunrise", "category": "creation and cosmos"},
    "53": {"symbol": "Sunset", "category": "creation and cosmos"},
    "54": {"symbol": "Thunder", "category": "creation and cosmos"},
    "55": {"symbol": "Valley", "category": "creation and cosmos"},
    "56": {"symbol": "Waterfall", "category": "creation and cosmos"},
    "57": {"symbol": "Whirlpool", "category": "creation and cosmos"},
    "58": {"symbol": "White", "category": "creation and cosmos"},
    "59": {"symbol": "Wind", "category": "creation and cosmos"},
    "60": {"symbol": "Yellow", "category": "creation and cosmos"},
    "61": {"symbol": "Zero", "category": "creation and cosmos"},
    "62": {"symbol": "Acorn", "category": "plant world"},
    "63": {"symbol": "Apple", "category": "plant world"},
    "64": {"symbol": "Flower", "category": "plant world"},
    "65": {"symbol": "Forest/Jungle", "category": "plant world"},
    "66": {"symbol": "Garden", "category": "plant world"},
    "67": {"symbol": "Grape", "category": "plant world"},
    "68": {"symbol": "Iris", "category": "plant world"},
    "69": {"symbol": "Lily", "category": "plant world"},
    "70": {"symbol": "Lotus", "category": "plant world"},
    "71": {"symbol": "Mandrake", "category": "plant world"},
    "72": {"symbol": "Mushroom", "category": "plant world"},
    "73": {"symbol": "Oak Tree", "category": "plant world"},
    "74": {"symbol": "Palm Tree", "category": "plant world"},
    "75": {"symbol": "Peach", "category": "plant world"},
    "76": {"symbol": "Pine Tree", "category": "plant world"},
    "77": {"symbol": "Pomegranate", "category": "plant world"},
    "78": {"symbol": "Roots", "category": "plant world"},
    "79": {"symbol": "Rose", "category": "plant world"},
    "80": {"symbol": "Seed", "category": "plant world"},
    "81": {"symbol": "Thistle", "category": "plant world"},
    "82": {"symbol": "Tree", "category": "plant world"},
    "83": {"symbol": "Ant", "category": "animal world"},
    "84": {"symbol": "Ape/Monkey", "category": "animal world"},
    "85": {"symbol": "Bat", "category": "animal world"},
    "86": {"symbol": "Bear", "category": "animal world"},
    "87": {"symbol": "Bird", "category": "animal world"},
    "88": {"symbol": "Bull", "category": "animal world"},
    "89": {"symbol": "Butterfly/Moth", "category": "animal world"},
    "90": {"symbol": "Cat", "category": "animal world"},
    "91": {"symbol": "Clam/Oyster", "category": "animal world"},
    "92": {"symbol": "Cobra", "category": "animal world"},
    "93": {"symbol": "Cockroach", "category": "animal world"},
    "94": {"symbol": "Cow", "category": "animal world"},
    "95": {"symbol": "Coyote", "category": "animal world"},
    "96": {"symbol": "Crab", "category": "animal world"},
    "97": {"symbol": "Crocodile", "category": "animal world"},
    "98": {"symbol": "Crow/Raven", "category": "animal world"},
    "99": {"symbol": "Deer", "category": "animal world"},
    "100": {"symbol": "Dog", "category": "animal world"},
    "101": {"symbol": "Dolphin", "category": "animal world"},
    "102": {"symbol": "Donkey", "category": "animal world"},
    "103": {"symbol": "Dove", "category": "animal world"},
    "104": {"symbol": "Dragon", "category": "animal world"},
    "105": {"symbol": "Eagle", "category": "animal world"},
    "106": {"symbol": "Elephant", "category": "animal world"},
    "107": {"symbol": "Falcon", "category": "animal world"},
    "108": {"symbol": "Fish", "category": "animal world"},
    "109": {"symbol": "Fly/Mosquito", "category": "animal world"},
    "110": {"symbol": "Fox", "category": "animal world"},
    "111": {"symbol": "Frog", "category": "animal world"},
    "112": {"symbol": "Goat", "category": "animal world"},
    "113": {"symbol": "Great Cats", "category": "animal world"},
    "114": {"symbol": "Hen/Rooster", "category": "animal world"},
    "115": {"symbol": "Honeybee", "category": "animal world"},
    "116": {"symbol": "Horse", "category": "animal world"},
    "117": {"symbol": "Kangaroo", "category": "animal world"},
    "118": {"symbol": "Mermaid", "category": "animal world"},
    "119": {"symbol": "Octopus", "category": "animal world"},
    "120": {"symbol": "Owl", "category": "animal world"},
    "121": {"symbol": "Peacock", "category": "animal world"},
    "122": {"symbol": "Pig", "category": "animal world"},
    "123": {"symbol": "Rabbit/Hare", "category": "animal world"},
    "124": {"symbol": "Rat/Mouse", "category": "animal world"},
    "125": {"symbol": "Scarab", "category": "animal world"},
    "126": {"symbol": "Scorpion", "category": "animal world"},
    "127": {"symbol": "Sheep", "category": "animal world"},
    "128": {"symbol": "Shell", "category": "animal world"},
    "129": {"symbol": "Snail", "category": "animal world"},
    "130": {"symbol": "Snake", "category": "animal world"},
    "131": {"symbol": "Spider", "category": "animal world"},
    "132": {"symbol": "Toad", "category": "animal world"},
    "133": {"symbol": "Turtle/Tortoise", "category": "animal world"},
    "134": {"symbol": "Unicorn", "category": "animal world"},
    "135": {"symbol": "Whale", "category": "animal world"},
    "136": {"symbol": "Wolf", "category": "animal world"},
    "137": {"symbol": "Worm", "category": "animal world"},
    "138": {"symbol": "Anthill", "category": "human world"},
    "139": {"symbol": "Antlers", "category": "human world"},
    "140": {"symbol": "Anus", "category": "human world"},
    "141": {"symbol": "Apron", "category": "human world"},
    "142": {"symbol": "Arm", "category": "human world"},
    "143": {"symbol": "Arrow", "category": "human world"},
    "144": {"symbol": "Ascent", "category": "human world"},
    "145": {"symbol": "Attic", "category": "human world"},
    "146": {"symbol": "Ax", "category": "human world"},
    "147": {"symbol": "Baldness", "category": "human world"},
    "148": {"symbol": "Basement/Cellar", "category": "human world"},
    "149": {"symbol": "Basket", "category": "human world"},
    "150": {"symbol": "Bath/Bathing", "category": "human world"},
    "151": {"symbol": "Beach", "category": "human world"},
    "152": {"symbol": "Beard", "category": "human world"},
    "153": {"symbol": "Bed/Bedroom", "category": "human world"},
    "154": {"symbol": "Beggar", "category": "human world"},
    "155": {"symbol": "Bell", "category": "human world"},
    "156": {"symbol": "Bicycle", "category": "human world"},
    "157": {"symbol": "Blood", "category": "human world"},
    "158": {"symbol": "Boat", "category": "human world"},
    "159": {"symbol": "Body", "category": "human world"},
    "160": {"symbol": "Bone", "category": "human world"},
    "161": {"symbol": "Bow and Arrow", "category": "human world"},
    "162": {"symbol": "Brain", "category": "human world"},
    "163": {"symbol": "Breast", "category": "human world"},
    "164": {"symbol": "Breath", "category": "human world"},
    "165": {"symbol": "Bridge", "category": "human world"},
    "166": {"symbol": "Broom", "category": "human world"},
    "167": {"symbol": "Burial", "category": "human world"},
    "168": {"symbol": "Calendar", "category": "human world"},
    "169": {"symbol": "Car", "category": "human world"},
    "170": {"symbol": "Carpet", "category": "human world"},
    "171": {"symbol": "Castle", "category": "human world"},
    "172": {"symbol": "Cave", "category": "human world"},
    "173": {"symbol": "Chain", "category": "human world"},
    "174": {"symbol": "Chair/Throne", "category": "human world"},
    "175": {"symbol": "Child", "category": "human world"},
    "176": {"symbol": "City", "category": "human world"},
    "177": {"symbol": "Claw/Nail", "category": "human world"},
    "178": {"symbol": "Cloister", "category": "human world"},
    "179": {"symbol": "Coffin", "category": "human world"},
    "180": {"symbol": "Comb", "category": "human world"},
    "181": {"symbol": "Compass", "category": "human world"},
    "182": {"symbol": "Cradle", "category": "human world"},
    "183": {"symbol": "Cremation", "category": "human world"},
    "184": {"symbol": "Cripple", "category": "human world"},
    "185": {"symbol": "Crossroads", "category": "human world"},
    "186": {"symbol": "Crown", "category": "human world"},
    "187": {"symbol": "Crucifixion", "category": "human world"},
    "188": {"symbol": "Decomposition", "category": "human world"},
    "189": {"symbol": "Descent", "category": "human world"},
    "190": {"symbol": "Disease", "category": "human world"},
    "191": {"symbol": "Dismemberment", "category": "human world"},
    "192": {"symbol": "Dream", "category": "human world"},
    "193": {"symbol": "Drowning", "category": "human world"},
    "194": {"symbol": "Drum", "category": "human world"},
    "195": {"symbol": "Ear", "category": "human world"},
    "196": {"symbol": "Earring", "category": "human world"},
    "197": {"symbol": "Excrement", "category": "human world"},
    "198": {"symbol": "Eye", "category": "human world"},
    "199": {"symbol": "Falling", "category": "human world"},
    "200": {"symbol": "Feather", "category": "human world"},
    "201": {"symbol": "Finger", "category": "human world"},
    "202": {"symbol": "Flute", "category": "human world"},
    "203": {"symbol": "Foot", "category": "human world"},
    "204": {"symbol": "Fountain", "category": "human world"},
    "205": {"symbol": "Gate/Door", "category": "human world"},
    "206": {"symbol": "Glass", "category": "human world"},
    "207": {"symbol": "Gossip", "category": "human world"},
    "208": {"symbol": "Grail", "category": "human world"},
    "209": {"symbol": "Hair", "category": "human world"},
    "210": {"symbol": "Hammer", "category": "human world"},
    "211": {"symbol": "Hand", "category": "human world"},
    "212": {"symbol": "Hanging", "category": "human world"},
    "213": {"symbol": "Harp/Lyre", "category": "human world"},
    "214": {"symbol": "Hat/Headdress", "category": "human world"},
    "215": {"symbol": "Head", "category": "human world"},
    "216": {"symbol": "Heart", "category": "human world"},
    "217": {"symbol": "Hearth", "category": "human world"},
    "218": {"symbol": "Helmet", "category": "human world"},
    "219": {"symbol": "Horns", "category": "human world"},
    "220": {"symbol": "House/Home", "category": "human world"},
    "221": {"symbol": "Hunting", "category": "human world"},
    "222": {"symbol": "Incense", "category": "human world"},
    "223": {"symbol": "Incest", "category": "human world"},
    "224": {"symbol": "Iron", "category": "human world"},
    "225": {"symbol": "Key", "category": "human world"},
    "226": {"symbol": "King/Queen", "category": "human world"},
    "227": {"symbol": "Kinship", "category": "human world"},
    "228": {"symbol": "Kiss", "category": "human world"},
    "229": {"symbol": "Kitchen", "category": "human world"},
    "230": {"symbol": "Knee", "category": "human world"},
    "231": {"symbol": "Knife/Dagger", "category": "human world"},
    "232": {"symbol": "Knot", "category": "human world"},
    "233": {"symbol": "Labyrinth", "category": "human world"},
    "234": {"symbol": "Ladder", "category": "human world"},
    "235": {"symbol": "Lamp/Candle", "category": "human world"},
    "236": {"symbol": "Leg", "category": "human world"},
    "237": {"symbol": "Liver", "category": "human world"},
    "238": {"symbol": "Lock", "category": "human world"},
    "239": {"symbol": "Mandala", "category": "human world"},
    "240": {"symbol": "Mask", "category": "human world"},
    "241": {"symbol": "Masturbation", "category": "human world"},
    "242": {"symbol": "Medicine", "category": "human world"},
    "243": {"symbol": "Menstruation", "category": "human world"},
    "244": {"symbol": "Metamorphosis", "category": "human world"},
    "245": {"symbol": "Milk", "category": "human world"},
    "246": {"symbol": "Mining", "category": "human world"},
    "247": {"symbol": "Mirror", "category": "human world"},
    "248": {"symbol": "Money", "category": "human world"},
    "249": {"symbol": "Mother", "category": "human world"},
    "250": {"symbol": "Mouth", "category": "human world"},
    "251": {"symbol": "Mummy", "category": "human world"},
    "252": {"symbol": "Murder/Slaying", "category": "human world"},
    "253": {"symbol": "Nail", "category": "human world"},
    "254": {"symbol": "Necklace", "category": "human world"},
    "255": {"symbol": "Net/Web", "category": "human world"},
    "256": {"symbol": "Niche", "category": "human world"},
    "257": {"symbol": "Nose", "category": "human world"},
    "258": {"symbol": "Orphan", "category": "human world"},
    "259": {"symbol": "Oven", "category": "human world"},
    "260": {"symbol": "Path/Road", "category": "human world"},
    "261": {"symbol": "Pearl", "category": "human world"},
    "262": {"symbol": "Phallus", "category": "human world"},
    "263": {"symbol": "Phoenix", "category": "human world"},
    "264": {"symbol": "Pillar/Column", "category": "human world"},
    "265": {"symbol": "Play", "category": "human world"},
    "266": {"symbol": "Plow", "category": "human world"},
    "267": {"symbol": "Poison", "category": "human world"},
    "268": {"symbol": "Pool", "category": "human world"},
    "269": {"symbol": "Potter", "category": "human world"},
    "270": {"symbol": "Prison", "category": "human world"},
    "271": {"symbol": "Prostitute", "category": "human world"},
    "272": {"symbol": "Purse", "category": "human world"},
    "273": {"symbol": "Ring", "category": "human world"},
    "274": {"symbol": "Scale", "category": "human world"},
    "275": {"symbol": "School", "category": "human world"},
    "276": {"symbol": "Scissors", "category": "human world"},
    "277": {"symbol": "Sewing", "category": "human world"},
    "278": {"symbol": "Sexual Union", "category": "human world"},
    "279": {"symbol": "Shape-Shifting", "category": "human world"},
    "280": {"symbol": "Ship/Wreck", "category": "human world"},
    "281": {"symbol": "Shoe", "category": "human world"},
    "282": {"symbol": "Skin", "category": "human world"},
    "283": {"symbol": "Soul", "category": "human world"},
    "284": {"symbol": "Sowing", "category": "human world"},
    "285": {"symbol": "Spear", "category": "human world"},
    "286": {"symbol": "Sperm", "category": "human world"},
    "287": {"symbol": "Spine", "category": "human world"},
    "288": {"symbol": "Stairway", "category": "human world"},
    "289": {"symbol": "Stranger", "category": "human world"},
    "290": {"symbol": "Street", "category": "human world"},
    "291": {"symbol": "Subway", "category": "human world"},
    "292": {"symbol": "Suicide", "category": "human world"},
    "293": {"symbol": "Swimming", "category": "human world"},
    "294": {"symbol": "Sword", "category": "human world"},
    "295": {"symbol": "Table", "category": "human world"},
    "296": {"symbol": "Tears", "category": "human world"},
    "297": {"symbol": "Teeth", "category": "human world"},
    "298": {"symbol": "Telephone", "category": "human world"},
    "299": {"symbol": "Temple", "category": "human world"},
    "300": {"symbol": "Thief/Robber", "category": "human world"},
    "301": {"symbol": "Thigh", "category": "human world"},
    "302": {"symbol": "Thread", "category": "human world"},
    "303": {"symbol": "Toilet", "category": "human world"},
    "304": {"symbol": "Tongue", "category": "human world"},
    "305": {"symbol": "Tower", "category": "human world"},
    "306": {"symbol": "Train", "category": "human world"},
    "307": {"symbol": "Transformation", "category": "human world"},
    "308": {"symbol": "Trumpet/Horn", "category": "human world"},
    "309": {"symbol": "Tunnel", "category": "human world"},
    "310": {"symbol": "Umbrella/Parasol", "category": "human world"},
    "311": {"symbol": "Urine", "category": "human world"},
    "312": {"symbol": "Veil", "category": "human world"},
    "313": {"symbol": "Vomit", "category": "human world"},
    "314": {"symbol": "Vulva", "category": "human world"},
    "315": {"symbol": "War/Warrior", "category": "human world"},
    "316": {"symbol": "Weaving/Spinning", "category": "human world"},
    "317": {"symbol": "Well", "category": "human world"},
    "318": {"symbol": "Wheel", "category": "human world"},
    "319": {"symbol": "Window", "category": "human world"},
    "320": {"symbol": "Womb", "category": "human world"},
    "321": {"symbol": "Work", "category": "human world"},
    "322": {"symbol": "Wound", "category": "human world"},
    "323": {"symbol": "Wreath", "category": "human world"},
    "324": {"symbol": "Actaeon", "category": "spirit world"},
    "325": {"symbol": "Adam and Eve", "category": "spirit world"},
    "326": {"symbol": "Adanas", "category": "spirit world"},
    "327": {"symbol": "Adonis", "category": "spirit world"},
    "328": {"symbol": "Agni", "category": "spirit world"},
    "329": {"symbol": "Airplane", "category": "spirit world"},
    "330": {"symbol": "Ajax", "category": "spirit world"},
    "331": {"symbol": "Akhenaten", "category": "spirit world"},
    "332": {"symbol": "Alchemy", "category": "spirit world"},
    "333": {"symbol": "Ancestor", "category": "spirit world"},
    "334": {"symbol": "Angel", "category": "spirit world"},
    "335": {"symbol": "Anthropos", "category": "spirit world"},
    "336": {"symbol": "Anubis", "category": "spirit world"},
    "337": {"symbol": "Aphrodite", "category": "spirit world"},
    "338": {"symbol": "Apollo", "category": "spirit world"},
    "339": {"symbol": "Apophis", "category": "spirit world"},
    "340": {"symbol": "Arachne", "category": "spirit world"},
    "341": {"symbol": "Archery", "category": "spirit world"},
    "342": {"symbol": "Architect", "category": "spirit world"},
    "343": {"symbol": "Argonauts", "category": "spirit world"},
    "344": {"symbol": "Argus", "category": "spirit world"},
    "345": {"symbol": "Artemis", "category": "spirit world"},
    "346": {"symbol": "Buddha", "category": "spirit world"},
    "347": {"symbol": "Chakras", "category": "spirit world"},
    "348": {"symbol": "Dakini", "category": "spirit world"},
    "349": {"symbol": "Furies", "category": "spirit world"},
    "350": {"symbol": "Ganesha", "category": "spirit world"},
    "351": {"symbol": "Ghost", "category": "spirit world"},
    "352": {"symbol": "Kabbalistic Tree", "category": "spirit world"},
    "353": {"symbol": "Quetzalcoatl", "category": "spirit world"},
    "354": {"symbol": "Vampire", "category": "spirit world"},
    "355": {"symbol": "Witch", "category": "spirit world"},
    "356": {"symbol": "Yakshi", "category": "spirit world"}
}